### PR TITLE
build: improve libedit handling for builds

### PR DESCRIPTION
**Pull request by compnerd**
Use the `FindLibEdit.cmake` module from LLDB to properly control where
the libedit libraries are searched for and linked from as well as where
the headers come from.  This uses the standard mechanisms which allows
users to control where libedit is pulled from (which is important for
cross-compilation).

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves [SR-NNNN](https://bugs.swift.org/browse/SR-NNNN).

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @jrose-apple @gottesmm @Rostepher @akyrtzi

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by jrose-apple** [comment]
`HAVE_UNICODE_LIBEDIT` was specifically checking for a libedit that supports Unicode. I don't see where the replacement code is doing that?

**Comment by compnerd** [comment]
Hmm, I didn't see anything in libedit that implied that the w* versions were optional.  Did I miss something?

**Comment by jrose-apple** [comment]
Maybe there was a really old libedit lying around on an older macOS, and then we copied this forward without thinking about it. If @akyrtzi isn't worried then I guess it's fine.

**Comment by compnerd** [comment]
Unfortunately, we do need two names for it - the preprocessor macro shouldn't use the CMake naming.  CMake uses `<package>_FOUND` while the preprocessing side tends to use `HAVE_<package>`.  Or perhaps I misunderstood the two names that you are referring to?

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by jrose-apple** [comment]
Oh, I didn't think about the fact that the second CMake name was still needed for `configure_file`. I do think the rename is a good idea but that's less important.

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by brentdax** [comment]
I think this change may have [broken the build on our 14.04 bots](https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-14_04//7681/console):

```
05:14:24 lib/libswiftImmediate.a(REPL.cpp.o):/home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-14_04/swift/lib/Immediate/REPL.cpp:function swift::runREPL(swift::CompilerInstance&, std::vector<std::string, std::allocator<std::string> > const&, bool): error: undefined reference to 'el_wgets'
05:14:24 lib/libswiftImmediate.a(REPL.cpp.o):/home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-14_04/swift/lib/Immediate/REPL.cpp:function swift::runREPL(swift::CompilerInstance&, std::vector<std::string, std::allocator<std::string> > const&, bool): error: undefined reference to 'el_wgets'
```
