### PR TITLE
[cxx-interop] Import virtual functions lazily

### PR DESCRIPTION
**Pull request by j-hui**
- **Explanation**: Previously, with `ImportCxxMembersLazily` enabled, `virtual` functions would still be imported eagerly. I had thought that importing them lazily might cause lookup problems because virtual functions are synthesized + handled specially, but it turns out I was wrong. Importing them lazily works just fine. This patch enables that.
- **Scope**: This patch only affects behavior when `ImportCxxMembersLazily` is enabled. which it is not by default.
- **Issues**: rdar://174587922
- **Risk**: Low
- **Testing**: Existing tests for `virtual` functions still pass, and I added a test case demonstrating/ensuring that `virtual` functions are now imported lazily. This patch set also includes some improvements for some virtual function tests. In particular, I expand a test case related to name lookup for a virtual function renamed via `SWIFT_NAME`.

### CODE REVIEW

**Comment by j-hui** [comment]
@swift-ci please smoke test

**Comment by j-hui** [comment]
@swift-ci please smoke test

**Comment by j-hui** [comment]
@swift-ci please smoke test

**Comment by j-hui** [comment]
@swift-ci please smoke test

File: test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift [hunk 1]
```diff
@@ -92,6 +95,8 @@ struct GoodStruct {
 //
 // NOTE-MISSING: func badStatic(_: Never) -> Never
 //
+// NOTE-MISSING: func badVirtual(_: Never) -> Never
```
Comment (hnrklssn) [inline test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:98]: Is this just a comment? Should it be a CHECK-NOT?

File: test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift [hunk 2]
```diff
@@ -176,12 +182,14 @@ void err(void) {
   gs.badArg(inc);
   auto inc2 = gs.getBad();
   GoodStruct::badStatic(inc2);
+  gs.badVirtual(inc);
```
Comment (hnrklssn) [inline test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:185]: does this actually provide any additional test coverage, given that it doesn't trigger any diagnostics?

File: test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift (hunk 1 above)
Comment (j-hui) [reply test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:98]: This is just a comment, indicating that it's missing from the module interface (alongside various other kinds of members) even though it should appear.

File: test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift (hunk 2 above)
Comment (j-hui) [reply test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:185]: Technically, yes, though I think they all get combined by Clang. This (and all the other statements in that file) leads to the `// cxx-error {{no type named 'enough'}}` expected diagnostics in the header file.

Comment (j-hui) [reply test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:185]: Though to your point I'm mostly adding that to `err.cpp` for completeness

**Review by Xazax-hun — APPROVED** [review]

**Review by egorzhdan — APPROVED** [review]

**Review by patrykstefanski — APPROVED** [review]

**Review by DougGregor — APPROVED** [review]

File: test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift (hunk 2 above)
Comment (hnrklssn) [reply test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:185]: This is just following existing practice for the test, so I think a follow up is fine, but it would be good to compile it separately so that we can very the diagnostics here as well.

Comment (j-hui) [reply test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:185]: Sorry, I don't think I understand what you mean by "compile it separately so that we can verify the diagnostics here as well."

`err.cpp` already is compiled separately, and the diagnostics are already checked in that header file (i.e., `cxx-error`).

Comment (hnrklssn) [reply test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:185]: How come we only get the swift side diagnostics once?

Comment (j-hui) [reply test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:185]: Sorry could you clarify which specific Swift diagnostics you're referring to?

Comment (hnrklssn) [reply test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:185]: This call site has no error, while [this seemingly identical call site](https://github.com/swiftlang/swift/pull/88551/changes#diff-69637e1c83d0e8c8855155c1a7fcc6c9fee09d95ef711de3aa92d8428b12b03aR241) gets an error. Why is that?

Comment (j-hui) [reply test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:185]: Oh, the corresponding Swift call site? i.e.,

```swift
  gs.badVirtual(inc)        // expected-swift-error {{has no member}}
```

This inconsistency exists is because C++ tends to _lack_ error messages where a user (or least where I) would normally expect one, when the root cause is a template instantiation failure.

Consider:

```c++
template <typename T> struct X { typename T::x t; };
struct Bar {};
struct Foo { X<Bar> foo(); };

void f(void) {
  Foo f;
  f.foo();
}
```

Compiling this gives:

```
hu.cpp:1:46: error: no type named 'x' in 'Bar'
    1 | template <typename T> struct X { typename T::x t; };
      |                                  ~~~~~~~~~~~~^
hu.cpp:7:5: note: in instantiation of template class 'X<Bar>' requested here
    7 |   f.foo();
      |     ^
1 error generated.
```

Clang only emits one error here, which points to the template the failed to instantiate, rather than the _reason_ that it failed to instantiate i.e., the note pointing to `f.foo()`. (Now that I'm trying to explain this, it is a bit odd that Clang doesn't emit the same note in this test. I'm not sure why that is.)

Meanwhile, in Swift, there are two errors because, *due to* the instantiation failure, we never successfully import the method `foo()` to the struct `Foo`, which leads to a member lookup failure. I could imagine feeding a Swift source location to Clang to emit a "requested here" note pointing to the Swift call site, but I don't think that's currently possible.

Comment (hnrklssn) [reply test/Interop/Cxx/class/invalid-members/function-members-with-invalid-types.swift:185]: ...I did not realise this call site was in C++. That explains it lol.

**Review by hnrklssn — APPROVED** [review]
