### PR TITLE
Fix Issue #63993 by improving out-of-place binding diagnostic and reflecting 'var' or 'let' binding pattern 

### LINKED ISSUE #63993: Improve out-of-place binding diagnostic to reflect whether the binding was written as 'var' or 'let'
For the following:

```swift
func bar(_ x: Int) -> Int { x }
if case bar(let x) = 0 {} // error: 'var' binding pattern cannot appear in an expression
```

we should say `'let' binding pattern` instead of `'var' binding pattern`.

### PR DESCRIPTION
**Pull request by Rajveer100**
Fixes Issue #63993

Added a new 'DescriptivePatternKind' declaration with its methods and functionality similar to 'DescriptiveDeclKind', thereby   allowing binding pattern check in the appropriate places for 'var' or 'let' and improving the overall diagnostics.

### CODE REVIEW

**Comment by Rajveer100** [comment]
@hamishknight 
In my understanding, these are the following additions that remain:

- `StringRef Pattern::getDescriptivePatternKindName(DescriptivePatternKind K)`
- `DescriptivePatternKind Pattern::getDescriptiveKind() const`
- +Misc.

File: include/swift/AST/DiagnosticEngine.h [hunk 1]
```diff
@@ -113,6 +114,7 @@ namespace swift {
     TypeRepr,
     FullyQualifiedType,
     PatternKind,
+    DescriptivePatternKind,
```
Comment (hamishknight) [inline include/swift/AST/DiagnosticEngine.h:117]: You should be able to remove `PatternKind` here and below, as `DescriptivePatternKind` should always be used for diagnostics.

**Review by hamishknight — COMMENTED** [review]
Definitely on the right track! The remaining items on your list sound good to me

File: include/swift/AST/DiagnosticEngine.h (hunk 1 above)
Comment (Rajveer100) [reply include/swift/AST/DiagnosticEngine.h:117]: Oh you mean it's a complete replacement rather than an addition? (Just for this file in context?)

File: include/swift/AST/Pattern.h [hunk 2]
```diff
@@ -50,6 +50,11 @@ enum : unsigned { NumPatternKindBits =
 /// Diagnostic printing of PatternKinds.
 llvm::raw_ostream &operator<<(llvm::raw_ostream &OS, PatternKind kind);
 
+enum class DescriptivePatternKind : uint8_t {
+  Var,
+  Let
```
[the remark this answers is not in the document]
Comment (Rajveer100) [reply include/swift/AST/Pattern.h:55]: Sure.

File: include/swift/AST/DiagnosticEngine.h (hunk 1 above)
Comment (hamishknight) [reply include/swift/AST/DiagnosticEngine.h:117]: Yes

File: include/swift/AST/DiagnosticEngine.h [hunk 3]
```diff
@@ -46,6 +46,7 @@ namespace swift {
   class SourceFile;
 
   enum class PatternKind : uint8_t;
```
Comment (hamishknight) [inline include/swift/AST/DiagnosticEngine.h:48]: I believe you should be able to remove this forward declaration now

File: include/swift/AST/DiagnosticEngine.h [hunk 4]
```diff
@@ -147,6 +148,7 @@ namespace swift {
       TypeRepr *TyR;
       FullyQualified<Type> FullyQualifiedTypeVal;
       PatternKind PatternKindVal;
```
Comment (hamishknight) [inline include/swift/AST/DiagnosticEngine.h:150]: You should be able to remove `PatternKindVal` now

File: include/swift/AST/Pattern.h [hunk 5]
```diff
@@ -50,6 +50,21 @@ enum : unsigned { NumPatternKindBits =
 /// Diagnostic printing of PatternKinds.
 llvm::raw_ostream &operator<<(llvm::raw_ostream &OS, PatternKind kind);
```
Comment (hamishknight) [inline include/swift/AST/Pattern.h:51]: Just noticed that this method can also be removed (and its implementation in Pattern.cpp)

File: lib/AST/Pattern.cpp [hunk 6]
```diff
@@ -68,6 +94,26 @@ StringRef Pattern::getKindName(PatternKind K) {
...
+    ENTRY(Paren, "paren");
+    ENTRY(Tuple, "tuple");
+    ENTRY(Named, "named");
+    ENTRY(Any, "any");
+    ENTRY(Typed, "typed");
+    ENTRY(Is, "is");
+    ENTRY(EnumElement, "enum-element");
+    ENTRY(OptionalSome, "optional-some");
+    ENTRY(Bool, "bool");
+    ENTRY(Expr, "expr");
```
Comment (hamishknight) [inline lib/AST/Pattern.cpp:109]: Could you preserve the existing printing behavior for these cases? What I mean by that is that they should use the same strings that are currently being produced from the `swift::operator<<(llvm::raw_ostream &OS, PatternKind kind)` method in this file. Once done, you can then delete that method.

**Review by hamishknight — COMMENTED** [review]
Looks great! I have a few more comments, but otherwise this looks good to me. A couple more things that also need doing before we can land this:

1. Can you run `git clang-format` over this change? If not already installed, you should be able to install `clang-format` with homebrew.
2. You'll need to update any tests that have had their diagnostics changed. Off the top of my head, I know there are a couple of cases in `test/Sema/redeclaration-checking.swift` that will need changing to expect `'let' binding pattern` instead of `'var' binding pattern` (and there's a `FIXME` comment you can now remove).

File: lib/AST/Pattern.cpp (hunk 6 above)
Comment (hamishknight) [reply lib/AST/Pattern.cpp:109]: It would also be great if you could change `"optional .Some matching pattern"` to `"optional pattern"` while you're here :) The case hasn't been called `.Some` in a long while, and I think `"optional pattern"` is clear enough (that's its official name anyway).

**Comment by Rajveer100** [comment]
> Looks great! I have a few more comments, but otherwise this looks good to me. A couple more things that also need doing before we can land this:
> 
> 1. Can you run `git clang-format` over this change? If not already installed, you should be able to install `clang-format` with homebrew.
> 2. You'll need to update any tests that have had their diagnostics changed. Off the top of my head, I know there are a couple of cases in `test/Sema/redeclaration-checking.swift` that will need changing to expect `'let' binding pattern` instead of `'var' binding pattern` (and there's a `FIXME` comment you can now remove).

Hey there, a little late on the reply, I will make the changes, thanks for the review!

**Comment by Rajveer100** [comment]
> 2. You'll need to update any tests that have had their diagnostics changed. Off the top of my head, I know there are a couple of cases in `test/Sema/redeclaration-checking.swift` that will need changing to expect `'let' binding pattern` instead of `'var' binding pattern` (and there's a `FIXME` comment you can now remove).

I don't find any such case in the mentioned file, no 'FIXME' comment as well. The only similar cases I observed were the ones with the 'redeclaration' issue or similar.

**Comment by Rajveer100** [comment]
Apart from that, I have done the changes.

**Comment by hamishknight** [comment]
@Rajveer100 This one here:

https://github.com/apple/swift/blob/70b982f9ca6d6ce87df12e2a5d5654d02514b4f4/test/Sema/redeclaration-checking.swift#L126-L130

and:

https://github.com/apple/swift/blob/70b982f9ca6d6ce87df12e2a5d5654d02514b4f4/test/Sema/redeclaration-checking.swift#L150-L152

**Comment by Rajveer100** [comment]
Hey! Looks like my codebase isn't updated since a while, cause the number of LOC in the file referenced is barely around ~120.

**Comment by hamishknight** [comment]
Ah that makes sense, be sure to `git pull --rebase` to avoid adding a merge to the branch

**Comment by Rajveer100** [comment]
Well, that's done, hope there aren't any more test files which need changes!

File: lib/AST/Pattern.cpp [hunk 7]
```diff
@@ -69,6 +65,28 @@ StringRef Pattern::getKindName(PatternKind K) {
...
+    ENTRY(Typed, "pattern type annotation");
+    ENTRY(Is, "prefix 'is' pattern");
+    ENTRY(EnumElement, "enum case matching pattern");
+    ENTRY(OptionalSome, "optional pattern");
+    ENTRY(Bool, "bool matching pattern");
+    ENTRY(Expr, "expression pattern");
+    ENTRY(Var, "'var' binding pattern");
+    ENTRY(Let, "'let' binding pattern");
+  }
+#undef Entry
```
Comment (hamishknight) [inline lib/AST/Pattern.cpp:86]: Just noticed this should be `#undef ENTRY`, other then that, this looks good to me

**Comment by Rajveer100** [comment]
Mistakenly had closed this pull request, I hope it doesn't affect anything! Apologies for that!

File: lib/AST/Pattern.cpp (hunk 7 above)
Comment (Rajveer100) [reply lib/AST/Pattern.cpp]: Fixed.

**Review by hamishknight — APPROVED** [review]
Wonderful, thank you!

**Comment by hamishknight** [comment]
> Well, that's done, hope there aren't any more test files which need changes!

Let's find out :)

@swift-ci please test

**Comment by Rajveer100** [comment]
Observed an issue!

I ran the tests specifically for the test file in context:

```
/Users/rajveersingh/Desktop/swift-project/swift/test/Sema/redeclaration-checking.swift:113:6: error: expected error not produced
  // expected-error@-1 {{invalid redeclaration of 'x'}}
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rajveersingh/Desktop/swift-project/swift/test/Sema/redeclaration-checking.swift:114:6: error: expected note not produced
  // expected-note@-2 {{'x' previously declared here}}
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rajveersingh/Desktop/swift-project/swift/test/Sema/redeclaration-checking.swift:117:6: error: expected error not produced
  // expected-error@-1 {{invalid redeclaration of 'x'}}
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rajveersingh/Desktop/swift-project/swift/test/Sema/redeclaration-checking.swift:118:6: error: expected note not produced
  // expected-note@-2 {{'x' previously declared here}}
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rajveersingh/Desktop/swift-project/swift/test/Sema/redeclaration-checking.swift:122:8: error: expected error not produced
    // expected-error@-1 {{invalid redeclaration of 'x'}}
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rajveersingh/Desktop/swift-project/swift/test/Sema/redeclaration-checking.swift:123:8: error: expected note not produced
    // expected-note@-2 {{'x' previously declared here}}
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rajveersingh/Desktop/swift-project/swift/test/Sema/redeclaration-checking.swift:130:6: error: expected error not produced
  // expected-error@-2 {{invalid redeclaration of 'x'}}
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/rajveersingh/Desktop/swift-project/swift/test/Sema/redeclaration-checking.swift:131:6: error: expected note not produced
  // expected-note@-3 {{'x' previously declared here}}
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Rajveer100** [comment]
```
Failed Tests (1):
  Swift(macosx-arm64) :: Sema/redeclaration-checking.swift


Testing Time: 0.41s
  Excluded: 8811
  Failed  :    1

4 warning(s) in tests

```

**Comment by hamishknight** [comment]
@Rajveer100 Did you rebuild after rebasing your branch? Those test failures sound like you have a build that was done before https://github.com/apple/swift/pull/63994

**Comment by hamishknight** [comment]
@swift-ci please test macOS

**Comment by Rajveer100** [comment]
Ah yes! 
Let me do that! :)

**Comment by hamishknight** [comment]
@swift-ci please test Linux

**Comment by Rajveer100** [comment]
A question! 
Could you briefly differentiate between normal tests and smoke tests, also when they are used and when not.

**Comment by hamishknight** [comment]
Sure, the details are documented in https://github.com/apple/swift/blob/main/docs/ContinuousIntegration.md#pull-request-testing. Personally I tend on the side of doing a full test unless the change is fairly trivial (e.g something like a light refactoring), though honestly it's probably overkill for a change like this.

**Comment by Rajveer100** [comment]
All checks passed!
