### PR TITLE
SILGen: Don't emit key path descriptors for properties with mutating getters [4.2]

### PR DESCRIPTION
**Pull request by slavapestov**
Fixes <https://bugs.swift.org/browse/SR-7176>, <rdar://problem/38439418>.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test

**Comment by slavapestov** [comment]
@parkera What happened here?

```
Foundation/NSArray.swift:670:20: error: value of type 'String' has no member 'hasSuffix'
19:07:33                 if filename.hasSuffix(ext) && filename.count > ext.count {
19:07:33                    ^~~~~~~~ ~~~~~~~~~
```

**Comment by parkera** [comment]
I don’t think we’ve changed this recently. Was there a change on String?

**Comment by slavapestov** [comment]
@milseman Any ideas?

**Comment by slavapestov** [comment]
@parkera In swift-4.2-branch, String.hasSuffix() is not defined on Linux. On master, it's implemented on both platforms. Can you remove the usage from Foundation?

**Comment by slavapestov** [comment]
The breakage was introduced by PR #1404

**Comment by slavapestov** [comment]
@parkera Actually it looks like the method was removed from the Swift stdlib so this is our fault. rdar://38424188

**Comment by milseman** [comment]
@airspeedswift changed the hasPrefix/hasSuffix code recently. Is it available on Linux?

**Comment by jckarter** [comment]
Thanks Slava!

**Comment by airspeedswift** [comment]
It's that the PR that added them to the stdlib for Linux needed picking to 4.2 because corelibs-foundation doesn't have a 4.2 branch. Testing https://github.com/apple/swift/pull/15258 now.

**Comment by slavapestov** [comment]
@swift-ci Please test Linux
