### ISSUE TITLE
Accessing `x.Type` forces `x` to be considered a type name

### ISSUE THREAD

**Issue by dabrahams** [swiftlang/swift#78988]
### Description

```
import IR

struct Register {
  let type: IR.Type // <== error: cannot find type 'IR' in scope
}
```

There's no actual problem here and I claim that in this context the compiler need not force `Type` to be treated as a keyword.  It should look up the base name `IR` first and see that it's a module.  If you disagree, then at least the error message can be improved.

### Reproduction

```swift
// module A 
struct Type {} 
```

```swift
// module B
import A
typealias Type = A.Type
```

### Expected behavior

Compile without error or at least give a better error message.  I spent an hour scratching my head before the workaround occurred to me.

### Environment

swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0

**Comment by broken-circle** [comment]
This still reproduces on `main`.

Module `A`:

```swift
public struct Type { }
```

Client:

```swift
import A

typealias Type = A.Type
```

I built module `A` with `swiftc -emit-module -module-name A` and compiled the client with `swiftc -typecheck -swift-version 6` and `-I` pointing at the directory holding the built module. The output is identical on `swift-6.0.3-RELEASE`, `swift-6.3.3-RELEASE` and `main-snapshot-2026-08-30`, on `arm64-apple-macosx26.0` for the latter two and `arm64-apple-macosx16.0` for 6.0.3:

```shell
1 | import A
2 |
3 | typealias Type = A.Type
  |                  |- error: cannot find type 'A' in scope
  |                  `- note: cannot use module 'A' as a type
```

The [type identifier grammar](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/types#Type-Identifier) and the [metatype type grammar](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/types#Metatype-Type) both match `A.Type`, and the reference states no rule for choosing between them. It says a type identifier "uses dot (`.`) syntax to refer to named types declared in other modules," so the behavior above seems to differ from what the reference describes.

SE-0491 added module selectors in 6.3, and `A::Type` compiles on `swift-6.3.3-RELEASE` and `main-snapshot-2026-08-30`.
