### PR TITLE
Add objc_retainAutoreleasedReturnValue()

### PR DESCRIPTION
**Pull request by spevans**
- This function has been duplicated in both swift-corelibs-libdispatch
  and swift-corelibs-foundation. Moving it to stdlib consolidates
  it and makes it available when not linking with Dispatch or
  Foundation.

- Only required for non-Apple targets as the Objc Runtime provides
  the appropiate function on Apple targets.

This needs to be tested/merged at the same time as https://github.com/apple/swift-corelibs-libdispatch/pull/258 which removes it from libdispatch otherwise there will be a duplicate symbol when testing libdispatch.

Foundation will be fixed in a followup PR but shouldn't have a problem with duplicate symbols as it currently links using `--allow-multiple-definition`

### CODE REVIEW

**Comment by gottesmm** [comment]
Are you sure that the right fix here isn't just to change the compiler?

**Comment by spevans** [comment]
@gottesmm That is probably the correct longterm fix and I was going to just alter it to emit a `swift_retain` instead of `objc_retainAutoreleasedReturnValue` however `swift_retain` doesn't return the original pointer. So I think any correct fix would require someone with more knowledge of the memory management.

Also I want to keep this change as simple as possible just to eliminate the duplicate symbols since it is  a multi repo change, a better solution can be done in a followup PR.

**Comment by gottesmm** [comment]
Ok. Can you file an SR for that so we can track that work?

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by jckarter** [comment]
I don't think we should do this; this is unnecessary churn and just defining the symbol is hiding serious bugs. We should fix the compiler.

**Comment by spevans** [comment]
I opened https://bugs.swift.org/browse/SR-5271 to track the correct fix.
