### PR TITLE
Revert "Disable validation-test/Python/build_swift.swift"

### PR DESCRIPTION
**Pull request by compnerd**
This reverts commit df2e553b82e8ba012a5c4545a899bdcd1e0d43c0.  Repair
the preset rather than disabling the tests.

Replace this paragraph with a description of your changes and rationale. Provide links to external references/discussions if appropriate.

Resolves SR-NNNN.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test tensorflow

**Comment by compnerd** [comment]
CC: @shabalind

**Review by dan-zheng — APPROVED** [review]

**Comment by compnerd** [comment]
I dont think that the sourcekit failures should be related?

**Comment by compnerd** [comment]
@swift-ci please clean test tensorflow

**Comment by burmako** [comment]
@compnerd Let me see whether tensorflow builds correctly and passes tests. https://github.com/apple/swift/pull/29347 was green when we merge but maybe something got screwed up.

**Comment by burmako** [comment]
@swift-ci please clean test tensorflow

**Comment by burmako** [comment]
It looks like `tensorflow` passes `utils/build-script --preset=tensorflow_test` on my gLinux workstation. Maybe that was a spurious error that got fixed by a clean build?

upd. Ah, wait a moment, it looks like the test failures are legit now? E.g. in https://ci-external.swift.org/job/swift-PR-TensorFlow-Linux/3458/console:

```
FAIL: Swift(linux-x86_64) :: Python/build_swift.swift (529 of 12640)
******************** TEST 'Swift(linux-x86_64) :: Python/build_swift.swift' FAILED ********************
Script:
--
: 'RUN: at line 10';   /usr/bin/python /home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/utils/build_swift/run_tests.py
--
Exit Code: 1

Command Output (stderr):
--
Traceback (most recent call last):
  File "/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/utils/build_swift/run_tests.py", line 19, in <module>
    import argparse
  File "/home/swiftci/jenkins/workspace/swift-PR-TensorFlow-Linux/swift/utils/build_swift/argparse/__init__.py", line 18, in <module>
    
ImportError: cannot import name ArgumentDefaultsHelpFormatter

--

********************
```

**Comment by burmako** [comment]
@compnerd I've disabled failing tests in https://github.com/apple/swift/pull/29503 to unblock everyone's work pending a proper investigation.

**Comment by burmako** [comment]
@swift-ci please clean test tensorflow

**Comment by compnerd** [comment]
I think that this is an infrastructure issue now - please switch to python 2.

**Comment by dan-zheng** [comment]
> I think that this is an infrastructure issue now - please switch to python 2.

I'm uninstalling Python 3 from the Linux CI machines. Let's see if tests pass with that change.

Linux toolchains should be built with Python 3, since that's required for [swift-jupyter](https://github.com/google/swift-jupyter). However, that's unrelated to apple/swift CI, which seems to require Python 2.

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please clean test tensorflow linux

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux gpu

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow linux gpu

**Comment by compnerd** [comment]
@dan-zheng I think that icu-devel was removed from the builder

**Comment by dan-zheng** [comment]
> @dan-zheng I think that icu-devel was removed from the builder

Yes. Unfortunately, I'm currently unable to ssh to the Linux GPU CI machine - it hangs. Let's try to debug the connection internally.

**Comment by dan-zheng** [comment]
Merging now to unblock progress, ignoring the Linux GPU CI failure.

We're currently unable to connect to CI machines for some reason. Once the connection issue is fixed, we can fix Linux CPU CI robustly (by installing missing `apt-get` dependencies).
