### PR TITLE
[Sema] Fix DerivedConformanceDifferentiable.cpp header order.

### PR DESCRIPTION
**Pull request by dan-zheng**
Fixes breakages introduced in https://github.com/apple/swift/pull/29908.
Breakages due to not running tests after `clang-format`.
Breakages not caught because `@swift-ci Please test tensorflow` was down.

---

Fixed errors:
```
[2/4] Building CXX object lib/Sema/CMakeFil....dir/DerivedConformanceDifferentiable.cpp.o
FAILED: lib/Sema/CMakeFiles/swiftSema.dir/DerivedConformanceDifferentiable.cpp.o
...
In file included from /home/danielzheng/swift-dev/swift/lib/Sema/DerivedConformanceDifferentiable.cpp:21:
/home/danielzheng/swift-dev/swift/lib/Sema/DerivedConformances.h:372:10: error: unknown type name 'GuardStmt'
  static GuardStmt *returnIfNotEqualGuard(ASTContext &C, Expr *lhsExpr,
         ^
/home/danielzheng/swift-dev/swift/lib/Sema/DerivedConformances.h:376:10: error: unknown type name 'GuardStmt'
  static GuardStmt *returnFalseIfNotEqualGuard(ASTContext &C, Expr *lhsExpr,
         ^
/home/danielzheng/swift-dev/swift/lib/Sema/DerivedConformances.h:379:10: error: unknown type name 'GuardStmt'
  static GuardStmt *
         ^
/home/danielzheng/swift-dev/swift/lib/Sema/DerivedConformances.h:408:38: error: use of undeclared identifier 'ASTNode'
  convertEnumToIndex(SmallVectorImpl<ASTNode> &stmts, DeclContext *parentDC,
                                     ^
/home/danielzheng/swift-dev/swift/lib/Sema/DerivedConformances.h:413:32: error: unknown type name 'EnumElementDecl'
  enumElementPayloadSubpattern(EnumElementDecl *enumElementDecl, char varPrefix,
                               ^
5 errors generated.
```

### CODE REVIEW

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@swift-ci Please test tensorflow

**Comment by dan-zheng** [comment]
`@swift-ci Please test tensorflow` still appears to be down.
`ninja check-swift` passes locally so I'll merge this now.
