### PR TITLE
Serialization: Don't drop generic type-alias type witness decls cross-module

### LINKED ISSUE #89909: Regression: cross-module lookup of an associated type witnessed by a protocol-extension `typealias` fails in Swift 6.4
## Summary

A protocol declares `associatedtype Action`, and the witness is supplied by a
`typealias Action = …` in a **protocol extension** (parameterized by the
conforming type). A conformer in a second module satisfies the requirement
implicitly through that extension. Referencing `Conformer.Action` from a *third*
module fails to type-check under Swift 6.4:

```
error: 'Action' is not a member type of struct 'Mid.Foo'
```

The same sources compile cleanly under Swift 6.3.2. Same-module references
resolve on both compilers; only cross-module qualified lookup of the
extension-witnessed associated-type alias regressed.

This reproduces with `swiftc` directly (no build system, no SwiftPM, no Xcode),
so it is a compiler frontend regression.

## Reproducer

Three source files, three modules, no dependencies, pure language semantics.

`Core.swift`:
```swift
public protocol Feature {
    associatedtype State
    associatedtype Action
}

extension Feature {
    public typealias Action = GenericAction<Self, State>
}

public enum GenericAction<F: Feature, State> {
    case state(State)
}
```

`Mid.swift` (conformer — no explicit `Action`):
```swift
import Core

public struct Foo: Feature {
    public typealias State = Int
}
```

`App.swift` (reference from a third module):
```swift
import Core
import Mid

public func useFooAction(_ action: Foo.Action) {}
```

Build each as its own module:
```sh
SDK=$(xcrun --sdk macosx --show-sdk-path)
swiftc -sdk "$SDK" -emit-module -module-name Core Core.swift -emit-module-path Core.swiftmodule
swiftc -sdk "$SDK" -emit-module -module-name Mid  -I . Mid.swift  -emit-module-path Mid.swiftmodule
swiftc -sdk "$SDK" -emit-module -module-name App  -I . App.swift  -emit-module-path App.swiftmodule
```

(A SwiftPM `Package.swift` with three targets `Core` → `Mid` → `App` reproduces
the same failure via `swift build`.)

## Expected vs. actual

**Expected** (Swift 6.3.2): all three modules emit successfully.

**Actual** (Swift 6.4), the `App` module fails:
```
App.swift:3:40: error: 'Action' is not a member type of struct 'Mid.Foo'
1 | import Core
2 | import Mid
3 | public func useFooAction(_ action: Foo.Action) {}
  |                                        `- error: 'Action' is not a member type of struct 'Mid.Foo'

Mid.Foo:1:15: note: 'Foo' declared here
```

## The three-module split is required

Collapsing any two of the modules compiles on both 6.3.2 and 6.4:

- Core + Mid merged (conformer in the same module as the extension), `App` references it → compiles.
- Mid + App merged (reference in the same module as the conformer) → compiles.
- All in one module → compiles.

The failure needs all three of: the extension that supplies the witness, the
conformer, and the reference site each in a **separate** module, with the
reference site importing both the witness module (`Core`) and the conformer
module (`Mid`).

## Workaround

Declare the `typealias` explicitly on each conformer that is referenced
cross-module:
```swift
public struct Foo: Feature {
    public typealias State = Int
    public typealias Action = GenericAction<Self, State>   // workaround
}
```
This compiles on 6.4. It has to be repeated on every conformer, which defeats
the purpose of supplying the witness once in a shared extension.

## Not a regression (scope guard)

A superficially similar failure is *not* a regression — it fails identically on
6.3.2 and 6.4: if the reference site imports only `Mid` but not `Core` (the
module that declares the extension), lookup fails with `cannot use type alias
'Action' here; 'Core' was not imported`. That is expected behavior. The
regression reported here specifically requires the reference site to import the
witness module and still fail member-type lookup on the cross-module conformer.

## Environment

Regressed in:
```
Apple Swift version 6.4 (swiftlang-6.4.0.20.104 clang-2100.3.20.102)
```
Last known good:
```
Apple Swift version 6.3.2 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
```
Sources and build commands are byte-identical between the two runs; only the
compiler differs. (These ship in Xcode 27.0 Beta 1 `27A5194q` and Xcode 26.5
respectively, selected via `DEVELOPER_DIR`.) Host: Apple Silicon, macOS.

### PR DESCRIPTION
**Pull request by jpsim**
## Summary

Fixes #89909, a Swift 6.4 regression where cross-module qualified lookup of an associated type whose witness is supplied by a `typealias` in a **protocol extension** fails with `'Action' is not a member type of struct 'Foo'`, when the extension, the conformer, and the reference site each live in a separate module.

```swift
// Core
public protocol Feature {
    associatedtype State
    associatedtype Action
}
extension Feature {
    public typealias Action = GenericAction<Self, State>
}
public enum GenericAction<F: Feature, State> { case state(State) }

// Mid
import Core
public struct Foo: Feature { public typealias State = Int }

// App
import Core
import Mid
public func useFooAction(_ action: Foo.Action) {} // error before this change
```

## Root cause

When deserializing a protocol conformance, the reference to a type-alias type witness declared in another module was conservatively dropped — the resolved type witness was kept, but the witness *declaration* was nulled out. This originates in #8896 (2017): cross-module typealias references were otherwise banned for resilience, and there was no cheap way to tell whether the typealias had changed, so the decl was dropped on the assumption that "having a declaration here isn't actually required by the rest of the compiler."

The drop fires whenever the typealias's declared interface type differs from the resolved witness type:

```cpp
!third->getDeclaredInterfaceType()->isEqual(second)
```

A *generic* type-alias witness such as `typealias Action = GenericAction<Self, State>` has declared interface type `GenericAction<Self, State>` (still parameterized), which can never equal the resolved concrete witness `GenericAction<Foo, Int>`. So the decl is dropped for **every** generic type-alias witness, not just for ones that genuinely changed — exactly the collateral damage the original comment flagged.

Since 62e4979691570df8e66452eed5be71ce69c7aa54 ("AST: Prefer associated types over protocol type aliases"), qualified lookup prefers the associated type over a protocol-extension type alias of the same name and routes through the conformance's type witness. With the witness declaration missing, `TypeChecker::lookupMemberType` treated it as circularity and bailed — producing the `'Action' is not a member type of struct 'Foo'` error.

## Fix

Remove the drop. The witness declaration is retained, and lookup resolves normally.

## Testing

- Added a regression test (`test/AssociatedTypeInference/cross_module_extension_typealias_witness.swift`) reproducing the three-module setup from the issue.
- Locally green across `Serialization`, `AssociatedTypeInference`, `multifile`, `ModuleInterface`, `Generics`, `decl`, `Sema`, and `Interpreter` (incl. `test_recursive_protocol_deserialization.swift`). The dropped-decl behavior never had a test of its own.

Fixes #89909

### CODE REVIEW

**Comment by slavapestov** [comment]
> When deserializing a conformance, the reference to a type-alias type witness declared in another module is intentionally dropped (Deserialization.cpp), on the assumption that "having a declaration here isn't actually required by the rest of the compiler." The resolved type witness itself is retained.

This looks like a terrible hack added in 2017 without even a test case, see https://github.com/swiftlang/swift/commit/3042e1f5edbd. I'm skeptical that it is truly necessary. What breaks if you just remove it?

```swift
    if (isa_and_nonnull<TypeAliasDecl>(third) &&
        third->getModuleContext() != getAssociatedModule() &&
        !third->getDeclaredInterfaceType()->isEqual(second)) {
      // Conservatively drop references to typealiases in other modules
      // that may have changed. This may also drop references to typealiases
      // that /haven't/ changed but just happen to have generics in them, but
      // in practice having a declaration here isn't actually required by the
      // rest of the compiler.
      third = nullptr;
    }
```

**Review by slavapestov — CHANGES_REQUESTED** [review]
(See comment above)

**Comment by jpsim** [comment]
You're right — removing it is the better fix, and nothing in the test suite depends on the drop.

Some archaeology: the block isn't really from 3042e1f5edbd (that commit only *relocated* it while reordering type-vs-value witness deserialization); it originates in #8896 (Jordan Rose, 2017), "Drop typealiases whose underlying types have changed." At the time cross-module typealias references were banned for resilience and there was no cheap way to detect a changed typealias inside a conformance, so the decl was dropped and the compiler relied on the canonical type.

The drop condition is `!third->getDeclaredInterfaceType()->isEqual(second)`. A *generic* typealias witness like `typealias Action = GenericAction<Self, State>` has declared interface type `GenericAction<Self, State>`, which never equals the resolved concrete witness `GenericAction<Foo, Int>` — so the decl gets dropped for **every** generic typealias witness, not just genuinely-changed ones (the original comment even flags this collateral damage). Combined with 62e4979 preferring associated types over protocol typealiases, lookup then had no decl to resolve and reported `'Action' is not a member type of struct 'Foo'`.

I've dropped the `lookupMemberType` workaround; the fix is now just removing the block. Full test suite is green locally (Serialization, AssociatedTypeInference, multifile, ModuleInterface, Generics, decl, Sema, Interpreter), including `test_recursive_protocol_deserialization.swift`. The dropped-decl path had no test of its own.

**Review by slavapestov — APPROVED** [review]

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
Do you mind cherry picking this to 6.4, since it fixes a regression?

**Comment by jpsim** [comment]
> Do you mind cherry picking this to 6.4, since it fixes a regression?

I'll cherrypick once this is merged so we have the full confidence of the CI test suite. Which incidentally, is it possible the macOS smoke test failed for reasons unrelated to my change?

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by jpsim** [comment]
Now that CI passed, I've opened a cherrypick PR for 6.4 here: https://github.com/swiftlang/swift/pull/90095
