### PR TITLE
Handle raw identifiers correctly in renamed APIs.

### PR DESCRIPTION
**Pull request by allevato**
This change adds support for raw identifiers when renaming APIs in Swift. This includes APIs defined in Swift (using the `@availability(..., renamed: ...)` attribute), as well as C/Objective-C (using either the `swift_name` attribute or APINotes). All of these take decl names as strings, and so the parsing for these requires that any decl name components (the base name or the argument labels) must have surrounding backticks in order to be treated correctly as a raw identifier.

Getting this working required some refactoring of `ParsedDeclName` since it previously assumed that it could just split around delimiters like `.`, `(`, and `:`. That's no longer guaranteed to work, so I've introduced backtick-aware split helpers to deal with this. Likewise, `ParsedDeclName` now keeps track of special decl base names (like `init` and `subscript`) to ensure that they're handled properly and not incorrectly escaped under the new logic.

This pairs with https://github.com/swiftlang/llvm-project/pull/12995 for the `swift_name` attribute and APINotes support.

### CODE REVIEW

**Comment by tshortli** [comment]
Some test coverage in `test/ASTGen/availability.swift` (and implementation if needed) for SwiftParser-based parsing would be good, too.

**Comment by egorzhdan** [comment]
https://github.com/swiftlang/llvm-project/pull/12995

@swift-ci please test

**Comment by susmonteiro** [comment]
> 13:36:16  CMake Error at stdlib/public/Cxx/CMakeLists.txt:64 (add_embedded_swift_target_library):
13:36:16    Unknown CMake command "add_embedded_swift_target_library".

Unrelated

**Comment by susmonteiro** [comment]
https://github.com/swiftlang/llvm-project/pull/12995

@swift-ci please test

**Comment by finagolfin** [comment]
I think you will need https://github.com/swiftlang/swift-build/pull/1444 also.

**Comment by susmonteiro** [comment]
https://github.com/swiftlang/llvm-project/pull/12995
https://github.com/swiftlang/swift-build/pull/1444

@swift-ci please test

**Comment by allevato** [comment]
Looks like some of the runs failed since they raced with the swift-build PR getting merged.

https://github.com/swiftlang/llvm-project/pull/12995

@swift-ci please test

**Comment by hnrklssn** [comment]
@allevato This patch changed how this return type is printed, but I can't seem to look up the type with the escaped name for some reason:
```
// header
#define __single __attribute__((__single__))
typedef struct foo *foo_t;
foo_t __single bar();

// swift
public func test() {
    let _: Int = bar() // error: cannot convert value of type '`foo_t __single`?' (aka 'Optional<OpaquePointer>') to specified type 'Int'
    let _: `foo_t __single` = bar() // error: cannot find type 'foo_t __single' in scope
}
```

Do you know what's happening here?

**Comment by allevato** [comment]
If you write `let _: foo_t = bar()`, does that compile?

Do you know what it printed before this change? Was it `` cannot convert value of type 'foo_t __single'? `` or `` cannot convert value of type 'foo_t'? ``? If it was the former, then it sounds like there may have already been a bug where the preprocessor token was getting pulled in as part of the type name and now we're just escaping it, because I wouldn't expect `let _: foo_t __single` to work either.

I'll try to take a look at this in the meantime.

**Comment by hnrklssn** [comment]
Yup, `let _: foo_t = bar()` works!
Before this change it printed `error: cannot convert value of type 'OpaquePointer?' to specified type 'Int'`.

**Comment by hnrklssn** [comment]
Ah yes I remember this bounds safety hack (by yours truly 😳) in clang now:
```
QualType VisitTypedefTypeLoc(const TypedefTypeLoc TL) {
    TypeLoc ActualTypeLoc = TL.getTypedefNameDecl()->getTypeSourceInfo()->getTypeLoc();
    ...
    QualType Res = VisitEither(ActualTypeLoc,
                               TL.getType().getSingleStepDesugaredType(Ctx));
    ...
    if (state.getDeclarator().getDeclSpec().getTypeSpecType() ==
        DeclSpec::TST_typename) {
      const char *Suffix;
      switch (DiagIndex) {
      case Bidi:      Suffix = " __bidi_indexable"; break;
      case Indexable: Suffix = " __indexable"; break;
      case Single:    Suffix = " __single"; break;
      case Unsafe:    Suffix = " __unsafe_indexable"; break;
      }
      // Create a dummy typedef with the new bounds. The bounds suffix is used
      // to avoid clashing in case the same typedef is used multiple times with
      // different bounds. The " " in the name makes it print as if the bounds
      // were outside the typedef. This also has the nice side-effect that it
      // cannot clash with typenames from source code.
      DeclarationName DN(&Ctx.Idents.get(
          (TL.getTypePtr()->getDecl()->getName() + Suffix).str()));
      LookupResult Result(S, DN, PAttr.getLoc(), Sema::LookupOrdinaryName);
      if (S.LookupName(Result, S.TUScope, /*AllowBuiltinCreation=*/true)) {
        NamedDecl *ND = Result.getFoundDecl();
        if (TypedefNameDecl *TD = dyn_cast<TypedefNameDecl>(ND))
          if (TD->getUnderlyingType() == Res)
            return S.Context.getTypedefType(TD);
      }
      TypedefDecl *NewTypedef = Ctx.buildImplicitTypedef(Res, DN.getAsString());
      S.IdResolver.AddDecl(NewTypedef);
      Res = Ctx.getTypedefType(NewTypedef, Res);
    }
    return Res;
}
```

This implicit typedef type isn't imported by ClangImporter, so name lookup doesn't work, but `desugarIfBoundsAttributed` also doesn't recognise this AST pattern. Long term we probably want to find another approach in clang, but for now I'll add this pattern to `desugarIfBoundsAttributed`.

**Comment by hnrklssn** [comment]
Fix in https://github.com/swiftlang/swift/pull/90065/changes#r3439035051
