### PR TITLE
Handle implicit member references inside extensions of nested types

### PR DESCRIPTION
**Pull request by jrose-apple**
- **Explanation:** Rewrites to name resolution in Swift 3.1 broke unqualified references to members of nested types within extensions (but outside function bodies) by producing an implicit reference to the containing type without sufficient context to resolve it. This used to work in Swift 3.0, so add a check for this specific case to resolve it properly.
- **Scope:** As far as I can tell this *only* affects the construct described above: unqualified references to members of nested types within extensions, outside function bodies.
- **Issue:** [SR-3847](https://bugs.swift.org/browse/SR-3847) / rdar://problem/30350835
- **Reviewed by:** @slavapestov
- **Risk:** Low. Any input that would have succeeded without this change should still succeed in the same way; this only adds new valid inputs.
- **Testing:** Added compiler regression tests, verified that the developer-submitted test cases no longer hit this issue.

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
"Slave went offline during the build" <- hm, terminology. :-/

@swift-ci Please test macOS

**Comment by jrose-apple** [comment]
...and again. What's going on, @shahmishal?

**Comment by shahmishal** [comment]
@jrose-apple  This failure was due to macOS-38 when offline during the build, I am going to take this node offline.

**Comment by shahmishal** [comment]
@swift-ci Please test macOS

**Comment by shahmishal** [comment]
```
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVOpenGLESTexture.h:23:2: error: malformed or corrupted AST file: 'SourceLocation remap refers to unknown module'
15:54:08 #include <OpenGLES/gltypes.h>
15:54:08  ^
15:54:08 /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVOpenGLESTexture.h:23:2: note: after modifying system headers, please delete the module cache at '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.1-branch/buildbot_incremental/swift-macosx-x86_64/./module-cache/18EZ0IW0QIRZ2'
15:54:08 #include <OpenGLES/gltypes.h>
15:54:08  ^
15:54:08 <module-includes>:1:9: note: in file included from <module-includes>:1:
15:54:08 #import "Headers/CoreImage.h"
15:54:08         ^
```

**Comment by shahmishal** [comment]
This might need clean build, should I re-trigger this build?

**Comment by jrose-apple** [comment]
I'm going to ask Ewa if I can take tomorrow to track this down with Bruno.

@swift-ci Please clean test macOS

**Comment by shahmishal** [comment]
@jrose-apple Thanks!
