### PR TITLE
Use the new transcoder in String(validating:as:) too

### PR DESCRIPTION
**Pull request by Catfish-Man**
Simple oversight. Fixes rdar://181958811, should be 50x+ faster

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please Apple Silicon benchmark

**Comment by Catfish-Man** [comment]
Looks like the change itself is probably ok but the benchmark needs an availability check: /Users/ec2-user/jenkins/workspace/swift-PR-macos/branch-main/swift/benchmark/single-source/UTF16Decode.swift:181:15: error: 'init(validating:as:)' is only available in iOS 18.0 or newer

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
@swift-ci please Apple Silicon benchmark

**Comment by Catfish-Man** [comment]
Interop/Cxx/stdlib/libcxx-module-interface.swift is failing, which appears to be unrelated

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
That test failure will be fixed by https://github.com/swiftlang/swift/pull/90626

**Comment by Catfish-Man** [comment]
And the other one will be fixed by https://github.com/swiftlang/swift/pull/90627

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Review by stephentyrone — APPROVED** [review]
