### PR TITLE
[rebranch] Adjust to "[Allocator] Drop RedZoneSize (non-sanitizer) and BytesAllocated members (#205711)"

### PR DESCRIPTION
**Pull request by gottesmm**
```
error: no member named 'getBytesAllocated' in 'llvm::BumpPtrAllocatorImpl<>'
  os << "Arena\t0\t" << Allocator.getBytesAllocated() << "\n";
                        ~~~~~~~~~ ^
```

The upstream commit dropped the hot-path BytesAllocated counter and its getBytesAllocated() accessor, migrating in-tree consumers (clangd, clang's PPMemoryAllocationsTest) to getTotalMemory(). Mirror that here for the four memory-statistics call sites.

getTotalMemory() is public on both the LLVM we build against today (stable/21.x) and the rebranch LLVM (stable/23.x), so this compiles before and after the rebranch with no version-conditional code.

The reported figures do change. getTotalMemory() sums whole slab sizes (computeSlabSize(i) = 4096 << min(30, i / 128)) instead of returning the exact bytes handed out, so it now also counts per-slab tail slack, alignment padding, and the unfilled remainder of the current slab. The new value is therefore an upper bound on the old one, overshooting by a 4096-byte floor for tiny arenas and by low single-digit percent once the geometric slab growth kicks in.

That is acceptable for the three call sites that only report numbers -- the arena dump, NumASTBytesAllocated, and NumSolverBytesAllocated / MaxSolverBytesAllocated -- none of which any test checks. The fourth, ASTContext::getSolverMemory(), also feeds the -solver-memory-threshold "expression too complex" cutoff, but at the 512 MB default the effective threshold moves by a fraction of a percent.

See https://github.com/llvm/llvm-project/commit/ca59c69132eef55cc42bf8854706590dfddf5584 (https://github.com/llvm/llvm-project/pull/205711).

### CODE REVIEW

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by gottesmm** [comment]
@swift-ci smoke test macOS platform

**Review by hamishknight — APPROVED** [review]

**Comment by gottesmm** [comment]
@swift-ci smoke test

**Comment by tbkka** [comment]
Is the test change here correct?  It's failing in PR #91439 with the error message showing on the wrong line.  (And I note that you only ran "smoke test" here which does not run validation tests.)

```
[2026-08-13T17:22:05.667Z] # .---command stderr------------
[2026-08-13T17:22:05.667Z] # | /Users/ec2-user/jenkins/workspace/swift-PR-macos-arm64/branch-main/swift/validation-test/Sema/type_checker_perf/slow/rdar120225470.swift:38:47: error: expected error not produced
[2026-08-13T17:22:05.667Z] # |               ZStack(alignment: .center) { // expected-error {{reasonable time}}
[2026-08-13T17:22:05.667Z] # |                                           ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2026-08-13T17:22:05.667Z] # |                                           
[2026-08-13T17:22:05.667Z] # | /Users/ec2-user/jenkins/workspace/swift-PR-macos-arm64/branch-main/swift/validation-test/Sema/type_checker_perf/slow/rdar120225470.swift:39:17: error: unexpected error produced: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
[2026-08-13T17:22:05.667Z] # |                 Image(uiImage: PHAsset.getUIImageFromPHAsset(asset: assetsFetchResult[j]()!)!)
[2026-08-13T17:22:05.667Z] # |                 ^
[2026-08-13T17:22:05.667Z] # `-----------------------------
```

**Comment by tbkka** [comment]
Ah.  I see this was reverted in #91452.
