### PR TITLE
[Visual C++] Provide alternative to array designators.

### PR DESCRIPTION
**Pull request by drodriguez**
Even if they are supported in GCC and Clang, C99 array designators are
not part of the current C++ standard (they will be in C++20), so they
are not supported in Visual C++.

This commit provides an alternative for Visual C++ (which should work in
other compilers) which doesn't use array designators.

I think Clang 10 will start printing a warning about this incorrect
usage.

Introduced in #28052 and started breaking Windows CI in https://ci-external.swift.org/job/oss-swift-windows-x86_64/1899 (it was broken before, but this error starts in that one).

### CODE REVIEW

**Comment by drodriguez** [comment]
@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
@swift-ci please smoke test

**Comment by drodriguez** [comment]
@swift-ci Please test Windows platform

**Review by owenv — APPROVED** [review]
Ugh, I thought this was part of the standard. LGTM to fix the build, but maybe we should just use the fallback everywhere to ensure we stay C++ 14 compliant. I can do that in a follow-up if need be

**Comment by drodriguez** [comment]
I will let the Windows PR testing finish with this code. I want to check that my local results are valid in the CI machine. I can remove the non-standard implementation and re-submit later with a comment about why the strange construct.

Also, if some C++ wizard knows a cleaner way to initialize a constexpr array, I would not mind learning about it.

**Comment by drodriguez** [comment]
The Windows CI went beyond the failure point just fine. Re-submitted with the non-standard implementation removed.

@swift-ci please smoke test

**Comment by owenv** [comment]
It seem like Clang doesn't like this line:
```
/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/lib/AST/DiagnosticEngine.cpp:140:37: error: array initializer must be an initializer list
18:19:13 static constexpr const char *const *educationalNotes[LocalDiagID::NumDiags] = EducationalNotes<LocalDiagID::NumDiags>().value;
18:19:13                                     ^
18:19:13 1 error generated.
```
Trying to work around that issue I'm also running into issues with "pointer to subject of temporary is not constexpr". I'm going to prepare a revert of my patch just in case.

**Comment by owenv** [comment]
clang accepts
```
static constexpr EducationalNotes<LocalDiagID::NumDiags> _EducationalNotes = EducationalNotes<LocalDiagID::NumDiags>();
static constexpr auto educationalNotes = _EducationalNotes.value;
```

I'm not sure if MSVC will like that use of auto though...

**Comment by drodriguez** [comment]
Gonna send that in a moment. I don't have the Windows machine at hand anymore, so I will trust that the CI will tell us if it works.

**Comment by drodriguez** [comment]
@swift-ci please smoke test

**Comment by drodriguez** [comment]
(I will go to bed, so anyone, feel free to merge if everything is green)

@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
https://ci-external.swift.org/view/Pull%20Request/job/swift-PR-windows/163/ is the CI job, but it haven't been linked to this PR for some reason.

**Comment by drodriguez** [comment]
I should have copy/pasted the solution provided, not try to type it from memory. Sigh.

@swift-ci please smoke test

**Comment by drodriguez** [comment]
@swift-ci please test Windows platform

**Comment by drodriguez** [comment]
Merging this one. Seems to work OK in the three platforms.
