### PR TITLE
[Concurrency] Fix missing trailing space in 'final' fix-it for non-final Sendable class

### PR DESCRIPTION
**Pull request by tosh7**
The `fixItInsert` for adding `final` to a non-final class conforming to `Sendable` (introduced in #83053) was missing a trailing space, causing the applied fix-it to produce `finalclass Foo` instead of `final class Foo`.

**Before (broken):**
```swift
class MyClass: Sendable {} // warning: non-final class 'MyClass' cannot conform to 'Sendable'
// Applying the fix-it produces:
finalclass MyClass: Sendable {} // compilation error
```

**After (fixed):**
```swift
class MyClass: Sendable {} // warning: non-final class 'MyClass' cannot conform to 'Sendable'
// Applying the fix-it produces:
final class MyClass: Sendable {} // correct
```

**Changes:**
- `lib/Sema/TypeCheckConcurrency.cpp`: Change `fixItInsert(classDecl->getStartLoc(), "final")` to `"final "` (add trailing space). Also fix the comment grammar: "An non-final" → "A non-final".
- `test/Concurrency/sendable_conformance_checking.swift`: Add fix-it content verification (`{{1-1=final }}` and `{{3-3=final }}`) to the two existing `concurrent_value_nonfinal_class` test cases that previously only checked the diagnostic message.

### CODE REVIEW

**Review by hamishknight — APPROVED** [review]
Thank you!

**Comment by hamishknight** [comment]
@swift-ci please smoke test
