### PR TITLE
[3.1][CodeComplete] Don't emit 'override' in protocol extension

### PR DESCRIPTION
**Pull request by rintaro**
Cherry-pick #7140 

- **Explanation:** In code-completion,
  - Don't emit any inherited declarations in protocol declarations because we don't want them.
  - Don't emit `override` keyword in protocol `extension`s because it's invalid.
- **Scope:** Affects code-completion clients.
- **Issue:** N/A
- **Reviewed by:** @benlangmuir https://github.com/apple/swift/pull/7140#issuecomment-276133328
- **Risk:** Low.
- **Testing:** Added regression tests.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test OS X Platform

**Comment by rintaro** [comment]
module cache problem?
```
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CIImage.h:10:9: note: while building module 'CoreVideo' imported from /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CIImage.h:10:
#import <CoreVideo/CoreVideo.h>
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CoreVideo.h"
        ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:39:10: note: in file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:39:
#include <CoreVideo/CVOpenGLESTexture.h>
         ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVOpenGLESTexture.h:23:2: error: malformed or corrupted AST file: 'SourceLocation remap refers to unknown module'
#include <OpenGLES/gltypes.h>
 ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVOpenGLESTexture.h:23:2: note: after modifying system headers, please delete the module cache at '/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.1-branch/buildbot_incremental/swift-macosx-x86_64/./module-cache/2VN2WIBCOLTD6'
#include <OpenGLES/gltypes.h>
 ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CoreImage.h"
        ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CoreImage.h:15:9: note: in file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CoreImage.h:15:
#import <CoreImage/CIImage.h>
        ^
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CIImage.h:10:9: error: could not build module 'CoreVideo'
#import <CoreVideo/CoreVideo.h>
        ^
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.1-branch/swift/stdlib/public/SDK/CoreImage/CoreImage.swift:14:19: error: could not build Objective-C module 'CoreImage'
@_exported import CoreImage  // Clang module
```
@swift-ci Please clean test OS X platform

**Comment by slavapestov** [comment]
@benlangmuir Do we actually want to take this for 3.1? It seems low risk but it's not a regression...

**Comment by rintaro** [comment]
@slavapestov 
It's a regression introduced in https://github.com/apple/swift/pull/4518.
But it's only for initializers in protocol extensions.

In Xcode8.2, this doesn't emit `override` keyword.
```swift
protocol BaseP {
    init(base: Int)
}
protocol TestP : BaseP {}
extension TestP {
    #^TOKEN^#
}
```

**Comment by benlangmuir** [comment]
I think it's a good fix to take for 3.1; as @rintaro says it is a regression.

**Comment by rintaro** [comment]
Thank you!
