### ISSUE TITLE
Method declared by extension macro is not visible to the compiler

### ISSUE THREAD

**Issue by adarovsky** [swiftlang/swift#74679]
### Description

Please check an attached example which creates a simple extension macro that adds "example" method to an entity.
Then, declare an entity with macro applied, and then reference that entity from the separate file. Unless an instance of that entity is created in that file, method added by macro cannot be found

[MultifileBugDemo.zip](https://github.com/user-attachments/files/15969184/MultifileBugDemo.zip)

### Reproduction

Macro
```swift
public struct ExampleMacro: ExtensionMacro {
    public static func expansion<D: DeclGroupSyntax, T: TypeSyntaxProtocol, C: MacroExpansionContext>(
        of node: AttributeSyntax,
        attachedTo declaration: D,
        providingExtensionsOf type: T,
        conformingTo _: [TypeSyntax],
        in context: C
    ) throws -> [ExtensionDeclSyntax] {
        let exampleFunction = try FunctionDeclSyntax("func example()") {
            """
            print("example")
            """
        }
        
        let extensionDecl = ExtensionDeclSyntax(extendedType: type) {
            MemberBlockItemSyntax(decl: exampleFunction)
        }
        
        return [extensionDecl]
    }
}
```

Entity.swift
```swift
import MultifileBugDemo

@ExampleMacro
struct ExampleEntity {
}
```

main.swift
```swift
func someTestFunc(entity: ExampleEntity) {
    // uncomment string below to make it compile
//        let e = ExampleEntity()
    entity.example()
}
```

compiler output:
```
~/test/MultifileBugDemo/Sources/MultifileBugDemoClient/main.swift:4:12: error: value of type 'ExampleEntity' has no member 'example'
    entity.example()
    ~~~~~~ ^~~~~~~
error: fatalError
```

### Expected behavior

An example should compile successfully

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

### Additional information

an example compiles successfully if uncomment
```swift
let e = ExampleEntity()
```
line

**Comment by hborla** [comment]
Your example compiles in Swift 6.0
