### ISSUE TITLE
swift fails to build with glibc 2.42

### ISSUE THREAD

**Issue by sergiodj** [swiftlang/swift#83715]
Hi,

I'm working on upgrading glibc to 2.42 on [Wolfi OS](https://github.com/wolfi-dev) and we currently package two versions of swift (in a private repository):

* 5.10.1
* 6.0.1

Both are currently failing to build with glibc 2.42, while succeeding with glibc 2.41.

The problem actually seems to be with the LLVM version that is bundled with swift, because this is the error I get:

```
2025/08/13 22:32:22 INFO FAILED: [code=1] lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.aarch64.dir/sanitizer_platform_limits_posix.cpp.o
2025/08/13 22:32:22 INFO /home/build/swift-project/build/Ninja-ReleaseAssert/llvm-linux-aarch64/bin/clang++ -DHAVE_RPC_XDR_H=0 -I/home/build/swift-project/llvm-project/compiler-rt/lib/sanitizer_common/.. -Wall -Wno-unused-parameter -O3 -DNDEBUG -std=c++17 -march=armv8-a -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -nostdinc++ -Wno-format -fno-rtti -Wframe-larger-than=570 -Wglobal-constructors -MD -MT lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.aarch64.dir/sanitizer_platform_limits_posix.cpp.o -MF lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.aarch64.dir/sanitizer_platform_limits_posix.cpp.o.d -o lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.aarch64.dir/sanitizer_platform_limits_posix.cpp.o -c /home/build/swift-project/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp 
2025/08/13 22:32:22 INFO /home/build/swift-project/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:471:31: error: invalid application of 'sizeof' to an incomplete type 'struct termio'
2025/08/13 22:32:22 INFO   unsigned struct_termio_sz = sizeof(struct termio);
2025/08/13 22:32:22 INFO                               ^     ~~~~~~~~~~~~~~~
2025/08/13 22:32:22 INFO /home/build/swift-project/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:471:45: note: forward declaration of '__sanitizer::termio'
2025/08/13 22:32:22 INFO   unsigned struct_termio_sz = sizeof(struct termio);
2025/08/13 22:32:22 INFO                                             ^
2025/08/13 22:32:22 INFO 1 error generated.
```

This problem affects LLVM/GCC and has been fixed by upstream at https://github.com/llvm/llvm-project/commit/59978b21ad9c65276ee8e14f26759691b8a65763 and https://github.com/llvm/llvm-project/commit/c99b1bcd505064f2e086e6b1034ce0b0c91ea5b9.

I'm very far from being an expert in swift or its build system, but would it be possible to cherry-pick the patches above?

Thanks.

**Comment by sergiodj** [comment]
Filed https://github.com/swiftlang/llvm-project/issues/11174, which I believe is a better place to discuss this problem.  I'm closing this issue now.
