### PR TITLE
Sema: Fix regression with 'Failure' type witness inference hack

### LINKED ISSUE #79367: [6.1] type does not conform to protocol 'AsyncIteratorProtocol'
### Description

A type that conforms to a protocol builds correctly from 6.0 and fails on 6.1. I'm also seeing the same error from current `main` 6.2.

I'm experimenting with some MRE test cases… but I'm not able to generalize this compiler error down to something less concrete. My only repro for now is specifically on `AsyncIteratorProtocol`.

From the 6.0 toolchain I can define a concrete implementation of `AsyncIteratorProtocol`:

```swift
struct AsyncIteratorImpl<Element>: AsyncIteratorProtocol {
  
}

extension AsyncIteratorImpl {
  func next() async throws -> Element? {
    fatalError()
  }
}
```

This compiles with no errors from 6.0.

This same exact code fails to compile from 6.1:

```text
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)
/Users/rick/Desktop/MyExecutable/Sources/main.swift:51:8: error: type 'AsyncIteratorImpl<Element>' does not conform to protocol 'AsyncIteratorProtocol'
49 | #if true
50 | 
51 | struct AsyncIteratorImpl<Element>: AsyncIteratorProtocol {
   |        |- error: type 'AsyncIteratorImpl<Element>' does not conform to protocol 'AsyncIteratorProtocol'
   |        `- note: add stubs for conformance
52 |   
53 | }

_Concurrency.AsyncIteratorProtocol.Element:2:16: note: protocol requires nested type 'Element'
1 | protocol AsyncIteratorProtocol {
2 | associatedtype Element}
  |                `- note: protocol requires nested type 'Element'
3 | 

_Concurrency.AsyncIteratorProtocol.Failure:3:18: note: protocol requires nested type 'Failure'
1 | protocol AsyncIteratorProtocol {
2 | @available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
3 |   associatedtype Failure : Error = any Error}
  |                  `- note: protocol requires nested type 'Failure'
4 | 
/Users/rick/Desktop/MyExecutable/Sources/main.swift:51:8: error: type 'AsyncIteratorImpl<Element>' does not conform to protocol 'AsyncIteratorProtocol'
49 | #if true
50 | 
51 | struct AsyncIteratorImpl<Element>: AsyncIteratorProtocol {
   |        |- error: type 'AsyncIteratorImpl<Element>' does not conform to protocol 'AsyncIteratorProtocol'
   |        `- note: add stubs for conformance
52 |   
53 | }

_Concurrency.AsyncIteratorProtocol.Element:2:16: note: protocol requires nested type 'Element'
1 | protocol AsyncIteratorProtocol {
2 | associatedtype Element}
  |                `- note: protocol requires nested type 'Element'
3 | 

_Concurrency.AsyncIteratorProtocol.Failure:3:18: note: protocol requires nested type 'Failure'
1 | protocol AsyncIteratorProtocol {
2 | @available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
3 |   associatedtype Failure : Error = any Error}
  |                  `- note: protocol requires nested type 'Failure'
4 | 
```

Removing the extension fixes the error:

```swift
struct AsyncIteratorImpl<Element>: AsyncIteratorProtocol {
  func next() async throws -> Element? {
    fatalError()
  }
}
```

### Reproduction

```swift
struct AsyncIteratorImpl<Element>: AsyncIteratorProtocol {
  
}

extension AsyncIteratorImpl {
  func next() async throws -> Element? {
    fatalError()
  }
}
```

### Expected behavior

No compiler errors on 6.1.

### Environment

Apple Swift version 6.1-dev (LLVM 36d7ebc48349af6, Swift c710b6d3de6a71b)
Target: arm64-apple-macosx15.0

Apple Swift version 6.2-dev (LLVM 5805166b4c9eb06, Swift 57234f8034befac)
Target: arm64-apple-macosx15.0

### PR DESCRIPTION
**Pull request by slavapestov**
We have a special hack to infer the 'Failure' type witness in 'AsyncIteratorProtocol' by considering the type of 'next()' witness.

In eaf06eae0e0a140b240a0b941c8add98dfc424db I added a check to fix some assertions that could happen if 'next()' was witnessed by a declaration in a protocol extension or superclass, which has a different generic signature.

However my check was too narrow, because it also prohibited this form of inference when 'next()' was in a different extension of the same nominal type.

Allow this again.

Fixes https://github.com/swiftlang/swift/issues/79367.
Fixes rdar://problem/145341658.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test
