### PR TITLE
Fix a couple of check-swift-validation-optimize test failures

### PR DESCRIPTION
**Pull request by slavapestov**
A bot runs tests in this configuration. One failure was a test where the relevant runtime call was optimized away. The other problem was a regression from https://github.com/apple/swift/pull/22736. I added a reduced test case that doesn't depend on the optimizer.

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by shahmishal** [comment]
```
16:31:25 Test Case 'TestURLSession.test_dataTaskWithHttpInputStream' started at 2019-02-23 00:31:07.067
16:31:25 /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift-corelibs-foundation/TestFoundation/TestURLSession.swift:170: error: TestURLSession.test_dataTaskWithHttpInputStream : XCTAssertEqual failed: ("1316 bytes") is not equal to ("1323 bytes") - Response Data and Data is not equal
16:31:25 Test Case 'TestURLSession.test_dataTaskWithHttpInputStream' failed (0.003 seconds)
```

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by slavapestov** [comment]
@swift-ci Please smoke test macOS

**Comment by shahmishal** [comment]
@swift-ci Please smoke test macOS

**Comment by slavapestov** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/1939
@swift-ci Please smoke test Linux

**Comment by slavapestov** [comment]
@swift-ci Please smoke test Linux
