### PR TITLE
[Threading][Runtime] Separate threading error function to fix link on Linux.

### LINKED ISSUE #59444: [Concurrency] `multiple definition of 'swift::threading::fatal'` after new Threading library
**Describe the bug**
`multiple definition of 'swift::threading::fatal(char const*, ...)'` linking failure happens since https://github.com/apple/swift/pull/59287

**To Reproduce**

Follow the below steps.

```
$ cat main.swift
import Dispatch

@main
struct Main {
  static func main() async {}
}

$ /home/katei/.ghq/github.com/kylef/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-06-13-a/usr/bin/swiftc -parse-as-library -static-stdlib
error: link command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld.gold: error: /home/katei/.ghq/github.com/kylef/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-06-13-a/usr/lib/swift_static/linux/libswiftCore.a(Errors.cpp.o): multiple definition of 'swift::threading::fatal(char const*, ...)'
/usr/bin/ld.gold: /home/katei/.ghq/github.com/kylef/swiftenv/versions/DEVELOPMENT-SNAPSHOT-2022-06-13-a/usr/lib/swift_static/linux/libswift_Concurrency.a(ThreadingError.cpp.o): previous definition here
```

**Expected behavior**

No link failure

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Swift Version: `DEVELOPMENT-SNAPSHOT-2022-06-13-a`

### PR DESCRIPTION
**Pull request by al45tair**
On Linux it seems that the linker objects, probably because of link order, to the definition of `swift::threading::fatal()` being in both static libraries.  Fix by moving `swift::threading::fatal()` to its own file in the main runtime as well as the Concurrency runtime.

Fixes #59444.

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci Please smoke test

**Review by mikeash — APPROVED** [review]
