### PR TITLE
Further workaround for priority mishandling in runtime.

### PR DESCRIPTION
**Pull request by varungandhi-apple**
See rdar://79378762, SR-14802, SR-14841, SR-14875.

This doesn't resolve all hangs, such as those occurring
due to explicit usage of priorities and certain other
situations where priorities seem to be causing issues
(rdar://79823345), but it does resolve some cases.

### CODE REVIEW

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test

**Review by aschwaighofer — APPROVED** [review]
Lgtm

**Comment by aschwaighofer** [comment]
@swift-ci smoke test linux

**Comment by aschwaighofer** [comment]
The failure on linux looks unrelated:
```
Test Case 'BuildPlanTests.testExplicitSwiftPackageBuild' started at 2021-07-16 10:56:40.049
SwiftDriver/ClangVersionedDependencyResolution.swift:165: Fatal error: Unresolved placeholder dependencies at planning stage: swiftPlaceholder("C")
Exited with signal code 4
```

**Comment by aschwaighofer** [comment]
@swift-ci smoke test linux

**Comment by varungandhi-apple** [comment]
Landing tracked by rdar://80688213.

**Comment by varungandhi-apple** [comment]
Linux failure fix is tracked by https://github.com/apple/swift/pull/38434

**Comment by varungandhi-apple** [comment]
@swift-ci smoke test

**Comment by aschwaighofer** [comment]
@swift-ci Please test windows
