### ISSUE TITLE
error: generic parameter 'Type' could not be inferred for projectedValue of @propertyWrapper

### ISSUE THREAD

**Issue by AleMaMi** [swiftlang/swift#61589]
**Describe the bug**

Following code is possible to compile with Swift 5.6, but not with Swift 5.7. Issue is in closure call of generic function with projectedValue of propertyWrapper as parameter.

```swift
@propertyWrapper
final class Generic<Type> {
    var wrappedValue: Type
    var projectedValue: Generic<Type> {
        self
    }
    init(wrappedValue: Type) {
        self.wrappedValue = wrappedValue
    }
}

protocol TypeProtocol {

}

struct TypeImplementation: TypeProtocol {

}

func using<Type>(_ generic: Generic<Type>) {
    print("using \(generic.self)")
}

func thisIsOK() {
    @Generic var instance: TypeImplementation = .init()
    using($instance)
}

func closureCall(_ closure: () -> Void) {
    closure()
}

func thisIsNotOK() {
    closureCall {
        @Generic var instance: TypeImplementation = .init()
        closureCall {
            using($instance) // this does not compile with Swift 5.7
        }
    }
}

thisIsOK()
thisIsNotOK()
```

**Steps To Reproduce**
1. Write code example into file, e.g. Example.swift
2. Compile&run with Swift 5.7: `$ swift Example.swift`

It generates error:
```
Example.swift:37:13: error: generic parameter 'Type' could not be inferred
            using($instance)
            ^
Example.swift:20:6: note: in call to function 'using'
func using<Type>(_ generic: Generic<Type>) {
```

**Expected behavior**
Code is possible to compile and run. It generates 2 line output
```
using Example.Generic<Example.TypeImplementation>
using Example.Generic<Example.TypeImplementation>
```

**Environment**
 - OS: macOS 12.6
 - Swift 5.7 from Xcode 14.0.1: swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50); Target: arm64-apple-macosx12.0
 - Swift 5.6 from RELEASE toolchain: Apple Swift version 5.6.3 (swift-5.6.3-RELEASE); Target: arm64-apple-macosx12.0

**Additional context**
It has been discovered in tests based on Quick framework, whole test spec is written as nested closures, example is artificial to pinpoint issue.

**Comment by AnthonyLatsis** [comment]
Works on `main`. @xedin Any ideas as to what fixed this?

**Comment by AnthonyLatsis** [comment]
A more reduced reproducer for 5.7:

```swift
@propertyWrapper
struct Wrapper<T> {
  var wrappedValue: T
  var projectedValue: Wrapper<T> { self }
}

struct S {}

let _ = {
  @Wrapper var s: S = S()

  // error: cannot reference invalid declaration '$s'
  // error: generic parameter 'T' could not be inferred
  let p: Wrapper = $s
}
```

**Comment by xedin** [comment]
Most likely https://github.com/apple/swift/pull/61052

**Comment by AnthonyLatsis** [comment]
Still works with those changes reverted.

**Comment by xedin** [comment]
Then it’s fixed by one of my earlier PRs that made property wrappers work in closures.

**Comment by AnthonyLatsis** [comment]
Found it, fixed by #60384. Thanks for the assistance!

**Comment by AnthonyLatsis** [comment]
Duplicate of #59295
