### PR TITLE
AST: Search multiple modules for `CGFloat` definition

### LINKED ISSUE #91816: Conversions between CGFloat and Double when building for macOS or iOS fails due to a compiler bug
### Description

When building a simple snippet that converts between `CGFloat` and `Double`, while importing `CoreFoundation`, triggers a compiler error that self reports as a compiler bug.

```
error: emit-module command failed with exit code 1 (use -v to see invocation)
float.swift:4:17: error: standard library type 'Double' is missing or broken; this is a compiler bug
2 |
3 | var y: CGFloat = 0.0
4 | var x: Double = y
  |                 `- error: standard library type 'Double' is missing or broken; this is a compiler bug
``` 

I believe this is a compiler bug, because the error message literally says "this is a compiler bug".

### Reproduction

```swift
import CoreFoundation

var y: CGFloat = 0.0
var x: Double = y
```

Using Xcode 27 beta 6 (Version 27.0 beta 6 (27A5252f)), I'm seeing the following compiler error when compiling targeting macOS:

```
float.swift:4:17: error: standard library type 'Double' is missing or broken; this is a compiler bug
2 |
3 | var y: CGFloat = 0.0
4 | var x: Double = y
  |                 `- error: standard library type 'Double' is missing or broken; this is a compiler bug
```

### Expected behavior

No compiler error.

### Environment

swift-driver version: 1.168.6 Apple Swift version 6.4 (swiftlang-6.4.0.33.1 clang-2100.3.33.1)
Target: arm64-apple-macosx26.0

### Additional information

It also fails when targeting iOS:

```bash
xcrun --sdk iphonesimulator swiftc -emit-module -module-name foo -o build/foo.swiftmodule  -target arm64-apple-ios18.0-simulator <snippet from above>
```

```
error: emit-module command failed with exit code 1 (use -v to see invocation)
float.swift:4:17: error: standard library type 'Double' is missing or broken; this is a compiler bug
2 |
3 | var y: CGFloat = 0.0
4 | var x: Double = y
  |                 `- error: standard library type 'Double' is missing or broken; this is a compiler bug
```

I searched for similar issues and found https://github.com/swiftlang/swift/issues/88070.

### PR DESCRIPTION
**Pull request by tshortli**
`KnownSDKTypes.def` declared `CGFloat` as a member of Foundation, but `CGFloat` may actually belong to CoreGraphics, CoreFoundation, or Foundation depending on the SDK and platform that the compilation targets. The assumption that `CGFloat` always belongs to Foundation caused this test case to break when building against the macOS SDK:

    import CoreFoundation

    var y: CGFloat = 0.0
    var x: Double = y // error: standard library type 'Double' is missing or broken; this is a compiler bug

Search all three modules for the definition of `CGFloat`.

Fixes a regression introduced by https://github.com/swiftlang/swift/pull/88004.

Resolves rdar://186096719 and https://github.com/swiftlang/swift/issues/91816.

### CODE REVIEW

**Comment by tshortli** [comment]
@swift-ci please test

File: lib/AST/ASTContext.cpp [hunk 1]
```diff
@@ -1908,6 +1912,49 @@ ConcreteDeclRef ASTContext::getRegexInitDecl(Type regexType) const {
   return ConcreteDeclRef(foundDecl, subs);
 }
 
+StructDecl *ASTContext::getCGFloatDecl() const {
+  if (getImpl().CGFloatDecl)
+    return getImpl().CGFloatDecl;
+
+  // CGFloat is declared by the CoreFoundation overlay on Darwin, and by
+  // Foundation on other platforms. Keep this list in sync with
+  // TypeBase::isCGFloat().
```
Comment (slavapestov) [inline lib/AST/ASTContext.cpp:1921]: Nitpick: You could extract the array into a global constant or something and use it in the other place

**Review by slavapestov — APPROVED** [review]
CGFloat, argh!

**Comment by tshortli** [comment]
@swift-ci please test Linux
