### ISSUE TITLE
@MainActor annotations are not applied correctly to modules with 6.2 compiler

### ISSUE THREAD

**Issue by m-cheung** [swiftlang/swift#83311]
### Description

There seems to be cases where the `@MainActor` annotation is not applied properly (or replaced unexpected). Specifically, the compiler seems to be producing unexpected outputs when `@MainActor` is used to annotate protocols that are subsequently exported as part of modules.

We have prepared a minimally reproducible code example and attached it as part of the "Reproduction" section.

### Reproduction

1. Create a file (e.g. API.swift) with the following content

```swift
@MainActor
public protocol Foo {
  func foo(block: @escaping @MainActor () throws -> Any)
}
```

2. Create a file (e.g. Impl.swift) with the following content

```swift
import test_Foo

public final class FooImpl: Foo {
  public func foo(block: @escaping @MainActor () throws -> Any) {}
}
```

3.  Create dir `builds` for the output
4. `xcrun swiftc -emit-module -module-name test_Foo -o builds/ Foo.swift`
5. `xcrun swiftc -emit-module -module-name FooImpl -o builds/ -I builds/ FooImpl.swift`

---

This produces the following error

```
error: emit-module command failed with exit code 1 (use -v to see invocation)
FooImpl.swift:3:20: error: type 'FooImpl' does not conform to protocol 'Foo'
1 | import test_Foo
2 |
3 | public final class FooImpl: Foo {
  |                    |- error: type 'FooImpl' does not conform to protocol 'Foo'
  |                    `- note: add stubs for conformance
4 |   public func foo(block: @escaping @MainActor () throws -> Any) {}
  |               `- note: candidate has non-matching type '(@escaping @MainActor () throws -> Any) -> ()'
5 | }
6 |

test_Foo.Foo.foo:2:17: note: protocol requires function 'foo(block:)' with type '(@escaping nonisolated(nonsending) () throws -> Any) -> ()'
1 | protocol Foo {
2 | @MainActor func foo(block: @escaping nonisolated(nonsending) () throws -> Any)}
  |                 `- note: protocol requires function 'foo(block:)' with type '(@escaping nonisolated(nonsending) () throws -> Any) -> ()'
```

Which seems to indicate that instead of expecting `@MainActor` it is expecting something totally different.

### Expected behavior

I would expect this code to compile successfully

### Environment

swift-driver version: 1.127.10 Apple Swift version 6.2 (swiftlang-6.2.0.14.8 clang-1700.3.14.6)
Target: arm64-apple-macosx15.0

### Additional information

This snippet of code did previously compile in `swift-driver version: 1.120.5 Apple Swift version 6.1 (swiftlang-6.1.0.110.21 clang-1700.0.13.3)` (or the Swift compiler which shipped as part of Xcode 16.3.0). We noticed this issue as we were preparing our project for Xcode 26.

---

This problem does not occur when the protocol and the class files are compiled as a single module. That is `xcrun swiftc -emit-module -module-name Foo -o builds/ Foo.swift FooImpl.swift` succeeds.

---

Additionally, we cannot explain why the following changes will allow the code to compile

```swift
@MainActor
public final class FooImpl: Foo {
  public func foo(block: @escaping @MainActor () throws -> Any) {}
}
```

to

```swift
public final class FooImpl: Foo {
  @MainActor public func foo(block: @escaping @MainActor () throws -> Any) {}
}
```

This does not seem to resolve the issue for all cases that we have encountered, but it does work for this minimally reproducible example.

**Comment by allevato** [comment]
@DougGregor @hborla Is this a bug in 6.2 or am I misreading something? The isolation attribute being wrong in the diagnostic seems odd.

**Comment by hborla** [comment]
I think @xedin just fixed this - it was a serialization issue (https://github.com/swiftlang/swift/pull/83048). Pavel, can you please confirm this is the same issue?

**Comment by allevato** [comment]
Can verify that it appears fixed with the latest 6.2 snapshot. The following commands succeed using the sources from the original issue above:

```shell
$ swiftly use 6.2-snapshot-2025-07-26                                                                  
The global default toolchain has been set to `6.2-snapshot-2025-07-26` (was 6.1.2)
$ swiftly run swiftc -emit-module -module-name test_Foo -o builds/ Foo.swift
$ swiftly run swiftc -emit-module -module-name FooImpl -o builds/ -I builds/ FooImpl.swift
$
```

Thanks so much for the quick reply, @hborla !

**Comment by m-cheung** [comment]
Thank you @allevato and @hborla.

I was able to verify that this was addressed in the latest snapshot as well. I hope this will make it into the next release / the final release of Xcode 26.
