### PR TITLE
[CS] Don’t fail constraint generation for ErrorExpr or if type fails to resolve

### LINKED ISSUE #60029: Unresolved name causes "Failed to produce diagnostic for expression..." error
**Describe the bug**
Earlier, I was refactoring some code and was in the process of changing the name of a variable for a dictionary. Before I changed one of the references to the variable, I received the following error message:
```
Failed to produce diagnostic for expression; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project
```

I sometimes also see a `Cannot find '<#name#>' in scope` error, but inconsistently between environments. The error could be resolved by changing the expression to use the updated name, but for a moment I was concerned I had a much more complicated error.

**Steps To Reproduce**
1. Paste the following code into Xcode or an Xcode Playground (possibly only using Xcode 14 beta 3/the version of Swift it runs).
2. Attempt to build (or run in an Xcode Playground).
3. Check for described error message.

```
var newName: [Int : [Int]] = [:]

for (key, values) in oldName {
    for (idx, value) in values.enumerated() {
        print(key, idx, value)
    }
}
```
...

**Expected behavior**
I expect to not see a `Failed to produce diagnostic for expression` error for a simple unresolved name error.

**Screenshots**
Simplified Snippet in `.playground` file
simplified - in playground

Simplified Snippet in `.xcodeproj`
simplified - in xcodeproj

Original-ish Snippet (preserves intent and observed error message) in `.xcodeproj`
> While I'd usually appreciate the help, I do not need any comments on Swift best practices or correctness as this happened while I was refactoring someone else's code to ensure that it produces the intended result, is more readable, etc. Thanks for wanting to help though!
original-ish in xcodeproj

**Environment (please fill out the following information)**
 - OS: macOS 12.4
 - Xcode: Version 14.0 beta 3 (14A5270f)

**Additional Context**:
Original-ish code snippet in plain-text. Notes:
- there is a function parameter called `entityForRemoval` of type `Entity`
- there is a class property called `committedEntities` (the `correctName` in the simplified version) of type `[KeyType : [Entity]]`
- changing `entities` to `committedEntities` resolves all errors
```
// Remove entity from parent and dictionary
entityForRemoval.removeFromParent()
for var (key, entitiesForKey) in entities {
    for (i, entity) in entitiesForKey.enumerated() {
        if (entity == entityForRemoval) {
            entitiesForKey.remove(at: i)
        }
    }
}
```

### LINKED ISSUE #60485: Failed to produce diagnostic for expression
**Describe the bug**
Xcode tells me to report a problem, the same if I compile with `swift build`

**Steps To Reproduce**
Problem can be reproduced with next small code snippet:
```
public struct Settings {
    public internal(set) var dictionary = [String: String]()
}

public struct Test {
    public internal(set) var dictionary = [String: String]()
    
    public init(settings: Settings) {
        for (key, value) in settings {
            
        }
    }
}
```
```
~/Dev/test/ swift --version
swift-driver version: 1.62.3 Apple Swift version 5.7 (swiftlang-5.7.0.123.8 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0
~/Dev/test/ swift build
Building for debugging...
/Users/me/Dev/test/Sources/test/test.swift:9:9: error: failed to produce diagnostic for expression; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project
        for (key, value) in settings {
        ^
```

**Expected behavior**
This works fine if I compile with Swift 5.6 and produce compilation error:
```
~/Dev/test/ swift build     
Building for debugging...
/Users/me/Dev/test/Sources/test/test.swift:9:29: error: tuple pattern cannot match values of non-tuple type '_'
        for (key, value) in settings {
                            ^
/Users/me/Dev/test/Sources/test/test.swift:9:29: error: for-in loop requires 'Settings' to conform to 'Sequence'
        for (key, value) in settings {
                            ^~~~~~~~
```

**Environment (please fill out the following information)**
 - OS: macOS 12.5 (21G72)
 - Xcode Version/Tag/Branch: Xcode 14 beta 5
 - Swift compiler: (see steps to reproduce)

### PR DESCRIPTION
**Pull request by ahoppen**
Instead of failing constraint generation by returning `nullptr` for an `ErrorExpr` or returning a null type when a type fails to be resolved, return a fresh type variable. This allows the constraint solver to continue further and produce more meaningful diagnostics.

Most importantly, it allows us to produce a solution where previously constraint generation for a syntactic element had failed, which is required to type check multi-statement closures in result builders inside the constraint system.

Resolves: https://github.com/apple/swift/issues/60029
Resolves: https://github.com/apple/swift/issues/60485

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

File: lib/Sema/CSSimplify.cpp [hunk 1]
```diff
@@ -11208,8 +11208,17 @@ ConstraintSystem::simplifyApplicableFnConstraint(
   if (shouldAttemptFixes()) {
     if (auto *typeVar = type2->getAs<TypeVariableType>()) {
       auto *locator = typeVar->getImpl().getLocator();
-      if (typeVar->isPlaceholder() || hasFixFor(locator))
+      if (typeVar->isPlaceholder() || hasFixFor(locator)) {
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:11211]: Could you please do a couple of things here:

- Remove `typeVar->isPlaceholder()` check since it's always false because type variable cannot be a placeholder anymore
- Move whole `if (shouldAttemptFixes())` to just before `TypeMatchOptions subflags = getDefaultDecompositionOptions(flags);`
-  use `desugar2` instead of `simplifyType(type2);`

File: test/stmt/if_while_var.swift [hunk 2]
```diff
@@ -51,7 +51,9 @@ guard let _ = nonOptionalEnum() else { fatalError() } // expected-error{{initial
 let optional: String? = nil
 if case let optional? { _ = optional } // expected-error{{variable binding in a condition requires an initializer}}
 if case let .some(optional) { _ = optional } // expected-error{{variable binding in a condition requires an initializer}}
+                                             // expected-error@-1 {{type of expression is ambiguous without more context}}
 if case .some(let optional) { _ = optional } // expected-error{{variable binding in a condition requires an initializer}}
+                                             // expected-error@-1 {{type of expression is ambiguous without more context}}
```
Comment (xedin) [inline test/stmt/if_while_var.swift:56]: Why did this start producing `type of expression is ambiguous without more context`?

File: test/Sema/placeholder_type.swift [hunk 3]
```diff
@@ -110,13 +110,13 @@ extension Bar {
 }
 
 // FIXME: We should probably have better diagnostics for these situations--the user probably meant to use implicit member syntax
-let _: Int = _() // expected-error {{type placeholder not allowed here}} expected-error {{type of expression is ambiguous without more context}}
-let _: () -> Int = { _() } // expected-error 2 {{type placeholder not allowed here}} expected-error {{unable to infer closure type in the current context}}
+let _: Int = _() // expected-error {{type placeholder not allowed here}} expected-error {{could not infer type for placeholder}}
```
Comment (xedin) [inline test/Sema/placeholder_type.swift:113]: A request, could be done separately - we need to turn `type placeholder not allowed here` error into a fix and check whether it exists before recording `specify type for placeholder` because we'd only want to produce "not allowed here" error and not both.

File: lib/Sema/CSSimplify.cpp [hunk 4]
```diff
@@ -12898,6 +12907,7 @@ ConstraintSystem::SolutionKind ConstraintSystem::simplifyFixConstraint(
   case FixKind::SpecifyLabelToAssociateTrailingClosure:
   case FixKind::AllowKeyPathWithoutComponents:
   case FixKind::IgnoreInvalidResultBuilderBody:
+  case FixKind::IgnoreInvalidASTNode:
```
Comment (xedin) [inline lib/Sema/CSSimplify.cpp:12910]: The impact of this fix should be `10` to underscore how broken the expression is.

File: lib/Sema/CSDiagnostics.cpp [hunk 5]
```diff
@@ -4796,7 +4796,9 @@ bool MissingArgumentsFailure::diagnoseClosure(const ClosureExpr *closure) {
 
   auto *locator = getLocator();
   if (locator->isForContextualType()) {
-    funcType = getContextualType(locator->getAnchor())->getAs<FunctionType>();
+    if (auto type = getContextualType(locator->getAnchor())) {
```
Comment (xedin) [inline lib/Sema/CSDiagnostics.cpp:4799]: This is interesting - do you have an example which caused a crash due to missing null check?

**Review by xedin — CHANGES_REQUESTED** [review]

File: test/stmt/if_while_var.swift (hunk 2 above)
Comment (ahoppen) [reply test/stmt/if_while_var.swift:56]: I just investigated this failure and we had free type variables left in the solution when solving it. Changing the type variable returned by `getTypeForPattern` to allow binding to a hole fixes the issue. (CSGen.cpp:2330).

File: test/Sema/placeholder_type.swift (hunk 3 above)
Comment (ahoppen) [reply test/Sema/placeholder_type.swift:113]: Let’s do this in a follow-up PR.

File: test/stmt/if_while_var.swift (hunk 2 above)
Comment (xedin) [reply test/stmt/if_while_var.swift:56]: Perfect!

File: test/Sema/placeholder_type.swift (hunk 3 above)
Comment (xedin) [reply test/Sema/placeholder_type.swift:113]: Sounds good!

File: lib/Sema/CSDiagnostics.cpp (hunk 5 above)
Comment (ahoppen) [reply lib/Sema/CSDiagnostics.cpp:4799]: This is something the stress tester found while I migrated to type check multi-statement closure bodies inside AST-transformed result builders. I’ll remove this check and 
```swift
  if (!getFromType()->is<TupleType>() || !getToType()->is<TupleType>()) {
     return false;
   }
```

and check whether we actually need them here.

File: lib/Sema/CSSimplify.cpp (hunk 1 above)
Comment (ahoppen) [reply lib/Sema/CSSimplify.cpp:11211]: > use `desugar2` instead of `simplifyType(type2);`

We need to simplify the type because `getFixedTypeRecursive` doesn’t simplify `AnyMetatypeType`s that have a type variable as instance type, so in `desugar2` the type variable won’t have been replaced by a placeholder yet.

**Comment by ahoppen** [comment]
@swift-ci Please smoke test macOS

**Comment by ahoppen** [comment]
@swift-ci Please SourceKit stress test

File: lib/Sema/CSSimplify.cpp (hunk 1 above)
Comment (xedin) [reply lib/Sema/CSSimplify.cpp]: Hm I keep forgetting about all the nuances of getFixedTypeRecursive vs. simplifyType. Maybe we should just call getFixedTypeRecursive on an instance type if type2 was a metatype for this new check.

**Comment by ahoppen** [comment]
@swift-ci Please smoke test macOS

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

**Review by xedin — APPROVED** [review]
Looks great, thank you! I have left a couple more minor comments inline.

**Comment by ahoppen** [comment]
@swift-ci Please smoke test

File: include/swift/Sema/CSFix.h [hunk 6]
```diff
@@ -295,6 +295,13 @@ enum class FixKind : uint8_t {
   /// Ignore result builder body if it has `return` statements.
   IgnoreResultBuilderWithReturnStmts,
 
+  /// Ignore `ErrorExpr` or `ErrorType` during pre-check.
+  IgnoreInvalidASTNode,
+
+  /// Ignore the a named pattern whose type we couldn't infer. This issue should
```
Comment (LucianoPAlmeida) [inline include/swift/Sema/CSFix.h:301]: "the" is extraneous here? 
```suggestion
  /// Ignore a named pattern whose type we couldn't infer. This issue should
```

File: include/swift/Sema/CSFix.h [hunk 7]
```diff
@@ -2693,6 +2720,57 @@ class IgnoreResultBuilderWithReturnStmts final
   }
 };
 
+class IgnoreInvalidASTNode : public ConstraintFix {
```
Comment (LucianoPAlmeida) [inline include/swift/Sema/CSFix.h:2723]: nit: Should this be final as well?
```suggestion
class IgnoreInvalidASTNode final : public ConstraintFix {
```

Comment (xedin) [reply include/swift/Sema/CSFix.h:2723]: Good catch!

**Comment by LucianoPAlmeida** [comment]
Resolves: https://github.com/apple/swift/issues/60485
