### ISSUE TITLE
source compatibility project Deferred fails with a compiler error

### ISSUE THREAD

**Issue by eeckstein** [swiftlang/swift#75498]
### Description

```
/build/swift-source-compat-suite/project_cache/Deferred/Sources/Deferred/Executor.swift:129:13: error: 'getCFRunLoop' is inaccessible due to 'internal' protection level
127 |             perform(body)
128 |         } else {
129 |             getCFRunLoop().submit(body)
    |             `- error: 'getCFRunLoop' is inaccessible due to 'internal' protection level
130 |         }
131 |     }
```

### Reproduction

build: https://ci.swift.org/job/swift-6.0-source-compat-suite-debug-ubuntu-2004/121

log: https://ci.swift.org/job/swift-6.0-source-compat-suite-debug-ubuntu-2004/121/artifact/build/swift-source-compat-suite/FAIL_vapor_routing_4.2_BuildSwiftPackage.log

### Expected behavior

should build fine

### Environment

CI

**Comment by kylesluder** [comment]
Caused by #4927.

**Comment by mickeyl** [comment]
I'd welcome a comment from the ones in power. Do you leave this regression open or is it planned to repair it? I can't move to Swift 6 on Linux because of that.
