### PR TITLE
Sema: Make Hashable-to-AnyHashable a Subtype rather than Conversion.

### PR DESCRIPTION
**Pull request by jckarter**
This admits AnyHashable in collection downcasts, though runtime support for the dynamic cast still appears to be incomplete. rdar://problem/27869032

### CODE REVIEW

**Comment by jckarter** [comment]
@swift-ci smoke test

**Comment by jckarter** [comment]
@DougGregor This look good for Swift 3?

**Comment by jckarter** [comment]
I don't think the Linux build failure is related. Is this happening on master?

```
******************** TEST 'Swift(linux-x86_64) :: FixCode/fixits-apply.swift' FAILED ********************
Script:
--
not '/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swift-linux-x86_64/bin/swift' -frontend -module-cache-path '/tmp/swift-testsuite-clang-module-cacheuuhmGW' -disable-objc-attr-requires-foundation-module -parse -target x86_64-unknown-linux-gnu /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/test/FixCode/fixits-apply.swift -emit-fixits-path /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/FixCode/Output/fixits-apply.swift.tmp.remap -I /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/test/FixCode/Inputs
c-arcmt-test /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/swift-linux-x86_64/test-linux-x86_64/FixCode/Output/fixits-apply.swift.tmp.remap | arcmt-test -verify-transformed-files /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/test/FixCode/fixits-apply.swift.result
--
Exit Code: 1

Command Output (stderr):
--
/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/swift/test/FixCode/fixits-apply.swift:8:3: error: 'Base' is not convertible to 'Derived'; did you mean to use 'as!' to force downcast?
b as Derived
~~^~~~~~~~~~
  as!
```

**Comment by jckarter** [comment]
Got the same Linux failure in #4338.

**Comment by DougGregor** [comment]
Looks great, thanks!
