### PR TITLE
[Diagnostics] Fix range of fix-its in verify mode

### PR DESCRIPTION
**Pull request by omochi**
This PR fix fix-its range of fix-its range in verify mode.

Current:

```
$ swift -frontend -typecheck -verify a.swift
a.swift:2:89: error: expected no fix-its; actual fix-it seen: {{14-14=else }}
  guard true { return } // unexpected-error {{expected 'else' after 'guard' condition}} {{none}}
                                                                                        ^~~~~~~
                                                                                        {{14-14=else }}
```
A range of fix-its is `{{none}`.

Patched:

```
$ swift -frontend -typecheck -verify a.swift
a.swift:2:89: error: expected no fix-its; actual fix-it seen: {{14-14=else }}
  guard true { return } // unexpected-error {{expected 'else' after 'guard' condition}} {{none}}
                                                                                        ^~~~~~~~
                                                                                        {{14-14=else }}
```

A range of fix-its is `{{none}}`.

This error is small for human.
But it's important when we use `-verify-apply-fixes`.

I also added test case for `-verify-apply-fixes`.
I couldn't find one already exists.

@gregomni @jrose-apple Please review this.
Original code is introduced in https://github.com/apple/swift/pull/674 .

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please smoke test

**Review by rintaro — APPROVED** [review]

**Comment by omochi** [comment]
@rintaro Thank you for review!
