### PR TITLE
Disable test that is failing CI

### PR DESCRIPTION
**Pull request by tbkka**
Hopefully, someone can fix this soon and we can re-enable it.

```
/Users/ec2-user/jenkins/workspace/oss-swift_tools-RA_stdlib-DA_test-device-non_executable/swift/test/IRGen/debug_scope_distinct.swift:12:11: error: CHECK: expected string not found in input
// CHECK: call void @llvm.dbg.value(metadata {{.*}} %[[ARG0]], metadata ![[VAR1:[0-9]+]], metadata !DIExpression(DW_OP_LLVM_fragment, 0, 64)), !dbg ![[LOC1:[0-9]+]]
          ^
<stdin>:1033:42: note: scanning from here
 %.sroa.013.0.copyload = load ptr, ptr %0, align 4, !dbg !305
                                         ^
<stdin>:1033:42: note: with "ARG0" equal to "\\.sroa\\.013\\.0\\.copyload"
 %.sroa.013.0.copyload = load ptr, ptr %0, align 4, !dbg !305
                                         ^
<stdin>:1040:2: note: possible intended match here
 call void @llvm.dbg.value(metadata i64 %4, metadata !299, metadata !DIExpression(DW_OP_LLVM_fragment, 40, 64)), !dbg !306
 ^
```

The input shows that line 1034 is this:
```
         1034:  call void @llvm.dbg.value(metadata ptr %.sroa.013.0.copyload, metadata !299, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 32)), !dbg !306
```
which differs in 32 vs. 64.  So I wonder if this is really an issue with integer size?

Link to a failing test:

https://ci.swift.org/job/oss-swift_tools-RA_stdlib-DA_test-device-non_executable/4234/

### CODE REVIEW

**Comment by tbkka** [comment]
CC: @asavonic

**Comment by tbkka** [comment]
Test was introduced in #66744 and was recently updated in #67699

**Comment by tbkka** [comment]
@swift-ci Please test

**Comment by asavonic** [comment]
@tbkka, can you please confirm that the test still fails after #67699? The link above shows the test failing for `watchos-armv7k` which should be disabled by `REQUIRES: CPU=arm64 || CPU=x86_64 || CPU=arm64e`.

**Comment by tbkka** [comment]
Looks like it's passing after #67699, so closing this.
