### PR TITLE
[test] Adjust SwiftNativeNSBase conditions

### PR DESCRIPTION
**Pull request by lorentey**
Adjust the conditions on the SwiftNativeNSBase test so that it runs when testing with the stdlib built directly from this repository.

rdar://problem/50413373

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
Failures are unrelated.

```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-master/swift/test/Frontend/crash-in-user-code.swift:5:11: error: CHECK: expected string not found in input
15:45:17 // CHECK: Stack dump:
15:45:17           ^
15:45:17 <stdin>:1:1: note: scanning from here
15:45:17 SOURCE_DIR/test/Frontend/crash-in-user-code.swift:15:2: warning: expression of type 'Int' is unused
15:45:17 ^
15:45:17 <stdin>:1:87: note: possible intended match here
15:45:17 SOURCE_DIR/test/Frontend/crash-in-user-code.swift:15:2: warning: expression of type 'Int' is unused
15:45:17                                                                                       ^
```

**Comment by lorentey** [comment]
The failure was addressed in https://github.com/apple/swift/pull/28373; retrying.

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
¯\_(ツ)_/¯

```
/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/llvm-project/llvm/lib/Support/PrettyStackTrace.cpp:57:39: error: implicit instantiation of undefined template 'std::atomic<unsigned int>'
15:30:49 static volatile std::atomic<unsigned> GlobalSigInfoGenerationCounter =
15:30:49                                       ^
15:30:49 /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/atomic_base.h:126:12: note: template is declared here
15:30:49     struct atomic;
15:30:49            ^
15:30:49 1 error generated.
```

**Comment by lorentey** [comment]
@swift-ci test

**Review by Catfish-Man — APPROVED** [review]
Looks good to me. Thank you!

**Comment by lorentey** [comment]
@swift-ci smoke test and merge
