### ISSUE TITLE
[stdlib] Unable to compile for PowerPC 64-bit

### ISSUE THREAD

**Issue by colemancda** [swiftlang/swift#78369]
### Description

Unable to compile the Swift Std Lib for `ppc64le` Linux with error: ` _Float16 is not supported on this target`

### Reproduction

Compile the Swift Std Library for riscv64-unknown-linux-gnu. I have [Buildroot](https://github.com/MillerTechnologyPeru/buildroot-swift) scripts setup to cross compile, but it should be reproducible building on host as well. This previously worked for Swift 5.7.1.

### Expected behavior

Should be able to compile for PPC64LE, as this previously worked with Swift 5.7.1

### Environment

Swift version 6.0.3 (swift-6.0.3-RELEASE)
Target: x86_64-unknown-linux-gnu

### Additional information

```
In file included from /workspaces/buildroot-swift/output/ppc64le/build/swift-6.0.3/stdlib/public/runtime/SwiftDtoa.cpp:76:
/workspaces/buildroot-swift/output/ppc64le/build/swift-6.0.3/include/swift/Runtime/SwiftDtoa.h:255:36: error: _Float16 is not supported on this target
  255 | size_t swift_dtoa_optimal_binary16(_Float16, char *dest, size_t length);
      |                                    ^
/workspaces/buildroot-swift/output/ppc64le/build/swift-6.0.3/stdlib/public/runtime/SwiftDtoa.cpp:348:36: error: _Float16 is not supported on this target
  348 | size_t swift_dtoa_optimal_binary16(_Float16 d, char *dest, size_t length) {
      |  
```

[logs_32476250395.zip](https://github.com/user-attachments/files/18259525/logs_32476250395.zip)

**Comment by barnejs** [comment]
> Fixed with `-DSWIFT_DTOA_PASS_FLOAT16_AS_FLOAT=1`

Thx!
