### ISSUE TITLE
[Source compatibility suite] GDRB failing to build older revisions - error: cannot find 'strcmp' in scope

### ISSUE THREAD

**Issue by justice-adams-apple** [swiftlang/swift#79796]
### Description

GRDB is failing to build with older revisions after the SDK update with the following error:
```
GRDB.swift/GRDB/Core/StatementAuthorizer.swift:99:19: error: cannot find 'strcmp' in scope
 97 |             // are prevented when the truncate optimization is disabled.
 98 |             // Let's authorize such deletions by returning SQLITE_OK:
 99 |             guard strcmp(cString1, "sqlite_master") != 0 else { return SQLITE_OK }
    |                   `- error: cannot find 'strcmp' in scope
100 |             guard strcmp(cString1, "sqlite_temp_master") != 0 else { return SQLITE_OK }
```

This is failing to build with the listed 4.2, 5.1, 5.3, 5.7 revisions of the project

### Reproduction

```swift
swift build --disable-sandbox --package-path GRDB.swift --verbose --configuration debug --build-tests -Xswiftc -swift-version -Xswiftc 5 -Xswiftc -enable-testing
```

### Expected behavior

Expected to build properly

### Environment

Apple Swift version 6.2-dev (LLVM 3a02857b159678d, Swift c91e29523420c00)
Target: x86_64-apple-macosx13.0

### Additional information

https://ci.swift.org/job/swift-main-source-compat-suite-debug/1050

**Comment by groue** [comment]
For what's worth, this `strcmp` issue went unnoticed in previous Swift releases.

Since the breaking change has been shipped, GRDB has been modified multiple times in order to make it work:

- https://github.com/groue/GRDB.swift/commit/344878c
- https://github.com/groue/GRDB.swift/commit/fcfdab2
- https://github.com/groue/GRDB.swift/commit/77a4d17

(Note that I find the use of `strcmp` justified, since we're dealing with C strings).
