### PR TITLE
[AutoDiff] Fix build error.

### PR DESCRIPTION
**Pull request by dan-zheng**
Fix build error introduced in https://github.com/apple/swift/pull/28892: https://ci.swift.org//job/oss-swift-incremental-RA-osx/9984

```
/Users/buildnode/jenkins/workspace/oss-swift-incremental-RA-osx/swift/lib/Sema/TypeCheckAttr.cpp:3558:5: error: non-void function 'typeCheckDerivativeAttr' should return a value [-Wreturn-type]
00:03:51     return;
00:03:51     ^
```

Caused by not re-running CI after https://github.com/apple/swift/pull/28879 was merged, sorry about that.

### CODE REVIEW

**Comment by dan-zheng** [comment]
@swift-ci Please smoke test

**Review by rxwei — APPROVED** [review]

**Comment by dan-zheng** [comment]
@rintaro: thanks for merging! Sorry the breakage affected you and others.
