### ISSUE TITLE
LLDB builds fail with: MangleClass is not a member of lldb_private::swift_demangle

### ISSUE THREAD

**Issue by weliveindetail** [swiftlang/swift#78488]
### Description

Windows bots are failing right now with a compile error in LLDB:
```
lldb\source\Plugins\LanguageRuntime\Swift\SwiftLanguageRuntimeDynamicTypeResolution.cpp(324): error C2039: 'MangleClass': is not a member of 'lldb_private::swift_demangle'
```

### Additional information

https://ci-external.swift.org/job/swift-main-windows-toolchain/938/ 
Full Log: [swift-main-windows-toolchain-938.log](https://github.com/user-attachments/files/18347092/swift-main-windows-toolchain-938.log)

https://ci-external.swift.org/job/swift-main-windows-toolchain-arm64/852/ 
Full Log: [swift-main-windows-toolchain-938.log](https://github.com/user-attachments/files/18347094/swift-main-windows-toolchain-938.log)

**Comment by weliveindetail** [comment]
Appears to be introduced with https://github.com/swiftlang/llvm-project/commit/c82cbb7627df089d9f69ae776d6eb09eae672240#diff-07d8ce63355507dbe937c04008d5a96b01cebee88e40f8aeb3978b502919b31a

@augusto2112 I guess we are missing a patch for `lldb/source/Plugins/TypeSystem/Swift/SwiftDemangle.h` here?

**Comment by weliveindetail** [comment]
This is not specific for Windows. LLDB bots for macOS fail as well: https://ci.swift.org/job/oss-lldb-incremental-macos-cmake/8765

**Comment by augusto2112** [comment]
I have a fix here https://github.com/swiftlang/llvm-project/pull/9812

**Comment by augusto2112** [comment]
This should be fixed now

**Comment by weliveindetail** [comment]
Yes works, thanks
