### PR TITLE
Sema: Three fixes for the new @escaping attribute (3.0)

### PR DESCRIPTION
**Pull request by slavapestov**
- Explanation: This patch fixes some issues that were reported with the change to make non-escaping closures the default and add an @escaping attribute. In particular, there was no way to have a non-escaping parameter of function type if the function type was an alias, or parenthesized. Furthermore, @escaping could not be applied to these types, and @escaping in invalid locations was not diagnosed and had no effect.
- Scope: Affects anyone writing code that operates on closures. This is a source-breaking change, and the current behavior is counter-intuititive, so this needs to be fixed.
- Risk: Medium.
- Testing: New tests added, existing tests updated for the new, more correct semantics of @escaping.
- Bugs: https://bugs.swift.org/browse/SR-2053, https://bugs.swift.org/browse/SR-2397

### CODE REVIEW

**Comment by slavapestov** [comment]
@swift-ci Please test os x

**Comment by slavapestov** [comment]
@milseman or @jrose-apple, can you review this for 3.0?

**Comment by slavapestov** [comment]
@tkremenek Do you know if anyone is looking at this?

```
/Users/buildnode/jenkins/workspace/swift-PR-osx/branch-swift-3.0-branch/swiftpm/Sources/Basic/Thread.swift:50:33: error: extraneous argument label 'block:' in call
16:18:03         self.thread = ThreadImpl(block: theTask)
16:18:03                                 ^~~~~~~~
16:18:03                                  
16:18:03 <unknown>:0: error: build had 1 command failures
```

**Comment by ematejska** [comment]
@slavapestov That failure is supposed to be fixed with https://github.com/apple/swift-package-manager/pull/612.

**Comment by ematejska** [comment]
@swift-ci Please test os x

File: lib/Sema/TypeCheckType.cpp [hunk 1]
```diff
@@ -1402,6 +1402,38 @@ static bool diagnoseAvailability(Type ty, IdentTypeRepr *IdType, SourceLoc Loc,
...
 
+/// Whether the given DC is a noescape-by-default context, i.e. not a property
+/// setter
+static bool isDefaultNoEscapeContext(const DeclContext *DC) {
+  auto funcDecl = dyn_cast<FuncDecl>(DC);
+  return !funcDecl || !funcDecl->isSetter();
+}
+
+// Hack to apply context-specific @escaping to an AST function type.
+static Type adjustFunctionExtInfo(DeclContext *DC,
```
Comment (milseman) [inline lib/Sema/TypeCheckType.cpp]: More specific name here, that is, adjust it to do what?

File: lib/Sema/TypeCheckType.cpp [hunk 2]
```diff
@@ -1948,29 +1973,54 @@ Type TypeResolver::resolveAttributedType(TypeAttributes &attrs,
...
 
-    bool defaultNoEscape = false;
-    if (isFunctionParam && !attrs.has(TAK_escaping)) {
-      defaultNoEscape = isDefaultNoEscapeContext(DC);
-    }
-
-    if (isFunctionParam && attrs.has(TAK_noescape) &&
-        isDefaultNoEscapeContext(DC)) {
+    if (attrs.has(TAK_noescape)) {
       // FIXME: diagnostic to tell user this is redundant and drop it
```
Comment (milseman) [inline lib/Sema/TypeCheckType.cpp]: FIXME is no longer relevant, as we actually detect this fact in the parser.

File: lib/Sema/TypeCheckType.cpp [hunk 3]
```diff
@@ -2428,9 +2484,12 @@ Type TypeResolver::resolveTupleType(TupleTypeRepr *repr,
   
   // If this is the top level of a function input list, peel off the
   // ImmediateFunctionInput marker and install a FunctionInput one instead.
-  auto elementOptions = withoutContext(options);
-  if (options & TR_ImmediateFunctionInput)
-    elementOptions |= TR_FunctionInput;
+  auto elementOptions = options;
+  if (!repr->isParenType()) {
```
Comment (jrose-apple) [inline lib/Sema/TypeCheckType.cpp]: Can you explain this part?

File: lib/Sema/TypeCheckType.cpp [hunk 4]
```diff
@@ -1983,11 +2033,11 @@ Type TypeResolver::resolveAttributedType(TypeAttributes &attrs,
         attrs.clearAttribute(i);
       }
     }
-  } 
-
-  // If we didn't build the type differently above, build it normally now.
-  if (!ty) ty = resolveType(repr, options);
-  if (!ty || ty->is<ErrorType>()) return ty;
```
Comment (jrose-apple) [inline lib/Sema/TypeCheckType.cpp]: Why don't we need this part anymore?

**Comment by milseman** [comment]
The code LGTM, could you otherwise elaborate on what the risk is from this change?

File: lib/Sema/TypeCheckType.cpp [hunk 5]
```diff
@@ -1983,11 +2033,11 @@ Type TypeResolver::resolveAttributedType(TypeAttributes &attrs,
...
+  } else if (hasFunctionAttr && fnRepr) {
+    for (auto i : FunctionAttrs)
```
Comment (jrose-apple) [inline lib/Sema/TypeCheckType.cpp]: What is this part doing?

File: lib/Sema/TypeCheckType.cpp [hunk 6]
```diff
@@ -1402,6 +1402,38 @@ static bool diagnoseAvailability(Type ty, IdentTypeRepr *IdType, SourceLoc Loc,
...
+
+  bool defaultNoEscape = isFunctionParam && isDefaultNoEscapeContext(DC);
+
+  // Desugar here
+  auto *funcTy = ty->castTo<FunctionType>();
+  auto extInfo = funcTy->getExtInfo();
+  if (defaultNoEscape && !extInfo.isNoEscape()) {
+    extInfo = extInfo.withNoEscape();
+
+    // We lost the sugar to flip the isNoEscape bit
```
Comment (jrose-apple) [inline lib/Sema/TypeCheckType.cpp]: Can you mark this as a FIXME, to introduce something like AttributedType later?

File: lib/Sema/TypeCheckType.cpp [hunk 7]
```diff
@@ -1402,6 +1402,38 @@ static bool diagnoseAvailability(Type ty, IdentTypeRepr *IdType, SourceLoc Loc,
   return false;
 }
 
+/// Whether the given DC is a noescape-by-default context, i.e. not a property
+/// setter
+static bool isDefaultNoEscapeContext(const DeclContext *DC) {
+  auto funcDecl = dyn_cast<FuncDecl>(DC);
+  return !funcDecl || !funcDecl->isSetter();
```
Comment (jrose-apple) [inline lib/Sema/TypeCheckType.cpp]: As noted on the other PR, what about subscript getter indices?

Comment (slavapestov) [inline lib/Sema/TypeCheckType.cpp]: You mean if a subscript is defined with a function type as its index? Wow. What _is_ the intended behavior here?

**Comment by slavapestov** [comment]
Working on a new patch now that adds comments to clarify things.

**Comment by slavapestov** [comment]
@swift-ci Please test os x

File: lib/Sema/TypeCheckType.cpp (hunk 1 above)
Comment (slavapestov) [inline lib/Sema/TypeCheckType.cpp]: Renamed to applyNonEscapingFromContext().

File: lib/Sema/TypeCheckType.cpp (hunk 6 above)
Comment (slavapestov) [inline lib/Sema/TypeCheckType.cpp]: Done.

File: lib/Sema/TypeCheckType.cpp (hunk 2 above)
Comment (slavapestov) [inline lib/Sema/TypeCheckType.cpp]: Removed

File: lib/Sema/TypeCheckType.cpp (hunk 5 above)
Comment (slavapestov) [inline lib/Sema/TypeCheckType.cpp]: It was there before, I think it's just clearing the attributes so that we don't diagnose about them later.

File: lib/Sema/TypeCheckType.cpp (hunk 3 above)
Comment (slavapestov) [inline lib/Sema/TypeCheckType.cpp]: Done.

**Comment by slavapestov** [comment]
For posterity: rdar://27918871

File: lib/Sema/TypeCheckType.cpp (hunk 7 above)
Comment (jrose-apple) [inline lib/Sema/TypeCheckType.cpp]: I hope no one does it, but if they do do it I would expect to be like function parameters: non-escaping by default and permitted to be marked escaping.

**Comment by jrose-apple** [comment]
What's the plan for optional function types, too? NTBF for Swift 3?
