### PR TITLE
Clang Importer: import all indirect fields.

### PR DESCRIPTION
**Pull request by Fruneau**
Until now, only indirect fields that didn't belong to a C union (somewhere
between the field declaration and the type in which it is indirectly
exposed) were imported in swift. This patch tries to provide an approach
that allows all those fields to be exposed in swift. However, the downside
is that we introduce new intermediate fields and types.

The main idea here is that we can simply expose the anonymous
struct/unions from which the indirect types are taken and then use swift
computed properties to access the content of those anonymous
struct/unions. As a consequence, each time we encounter an anonymous
struct or union, we actually expose it at `__Anonymous_field<id>` (where id
is the index of the field in the structure). At this point, we use the
existing mechanism to expose the type as
`__Unnamed_<struct|union>_<fieldname>`. Then, each indirect field is exposed
as a computed property.

The C object:
```c
 typedef union foo_t {
     struct {
         int a;
         int b;
     };
     int c;
 } foo_t;
```
Is imported as
```swift
 struct foo_t {
   struct __Unnamed_struct___Anonymous_field1 {
     var a : Int32
     var b : Int32
   }
   var __Anonymous_field1 : foo_t.__Unnamed_struct___Anonymous_field1
   var a : Int32 {
     get {
       return __Anonymous_field1.a
     }
     set(newValue) {
       __Anonymous_field1.a = newValue
     }
   }
   var b : Int32 {
     get {
       return __Anonymous_field1.b
     }
     set(newValue) {
       __Anonymous_field1.b = newValue
     }
   }
   var c : Int32
 }
```
This has the advantage to work for both struct and union, even in case we
have several nested anonymous struct/unions. This does not require to know
the size and/or the offset of the fields in the structures and thus can be
properly implemented using front-end data.

### CODE REVIEW

**Comment by slavapestov** [comment]
Excellent!

**Comment by jrose-apple** [comment]
Thanks for looking at this, @Fruneau! The reason it is the way it is today is because we wanted to avoid having to generate names for *types,* which can then show up in mangling and such. I'm concerned about tying names to declaration order. On the other hand, though, it's not too different from other kinds of "binary-compatible" changes you can make in C, like replacing one struct with another one that's layout-compatible. Hm.

cc @milseman

**Comment by slavapestov** [comment]
@jrose-apple We could ban users from referencing the types by name. If they don't appear in public declaration signatures they shouldn't get mangled either.

**Comment by slavapestov** [comment]
@swift-ci Please smoke test

**Comment by Fruneau** [comment]
@jrose-apple Thx for the feedback. I don't really think the patch is about generating type names, since the mechanism for generating type names was already in place (it was introduced in commit 023596783b1cbe915e3c584ccd9df46110fc9b36). This is more about renaming anonymous fields, which has the side effect of generating more type names since those fields were previously ignored.

**Comment by slavapestov** [comment]
It looks like this introduces a problem with duplicate members added somewhere?

```
/Users/buildnode/jenkins/workspace/swift-PR-osx-smoke-test/branch-master/swift/test/Interpreter/SDK/GLKit.swift:17:13: error: ambiguous use of 'x'
  print("<\(v.x) \(v.y) \(v.z) \(v.w)>")
            ^
GLKit._GLKVector4:27:16: note: found this candidate
    public var x: Float { get set }
               ^
GLKit._GLKVector4:4:16: note: found this candidate
    public var x: Float { get }
```

**Comment by Fruneau** [comment]
@slavapestov It looks like the GLKit worked-around the lack of indirect field exposition by adding swift extensions to some of their structures.

I don't know what the right approach is at this point. I can see several possibilities:
* have some new mechanism to avoid importing a member if we detect it is added by an extension (don't know if this is really feasible). Maybe this would look like some kind of weak symbols (weak as in `__attribute__((weak))`, not as ARC's weak)?
* make the feature opt-in (or opt-out, but that would require patching GLKit) using per-field attribute 
* hide the feature behind some "has_feature" or in a specific version (but again, that will require hiding patching the swift extension of GLKit)

**Comment by jrose-apple** [comment]
Since the GLKit overlay is also part of this repository, we can certainly just edit it if we get sign-off from some of the GLKit folks. I am worried about existing third-party libraries having done the same thing, though.

Another option would be to change overload resolution to allow overlays to shadow imported members, *or* to always prefer members in the original type over members in extensions. @rudkx, @DougGregor, any thoughts on those?

**Comment by slavapestov** [comment]
My preference is to fix the GLKit overlay and remove the workaround there. Another option is to only import indirect fields in Swift 4 mode.

I'm worried about introducing a one-off workaround to overload resolution to handle this case, it might be more trouble than it's worth.

**Comment by slavapestov** [comment]
We could also give the indirect members unique names, maybe with some kind of prefix.

But again, ugh... let's try to just fix GLKit and see if there is any additional fallout. We can always change the policy later.

**Comment by Fruneau** [comment]
Ho!

I just didn't see the overlay was part of the repository (I tried to grep `GLKVector4` which has no match in the gyb file).

**Comment by Fruneau** [comment]
@swift-ci Please smoke test

**Comment by CodaFi** [comment]
@Fruneau Unfortunately, that requires privileges.

@swift-ci please smoke test.

File: lib/ClangImporter/ImportDecl.cpp [hunk 1]
```diff
@@ -2544,6 +2659,25 @@ namespace {
 
         auto VD = cast<VarDecl>(member);
 
+        if (isa<clang::IndirectFieldDecl>(nd) || decl->isUnion()) {
+          // Don't import unconditionnaly unavailable fields that have
```
Comment (DougGregor) [inline lib/ClangImporter/ImportDecl.cpp]: Typo "unconditionnaly".

File: lib/ClangImporter/ImportDecl.cpp [hunk 2]
```diff
@@ -2544,6 +2659,25 @@ namespace {
...
+          for (auto attr : attrs) {
+            if (attr->isUnconditionallyUnavailable()) {
+              isUnconditionallyUnavailable = true;
+              break;
+            }
+          }
+          if (isUnconditionallyUnavailable) {
+            continue;
+          }
+        }
```
Comment (DougGregor) [inline lib/ClangImporter/ImportDecl.cpp]: This loop looks equivalent to `VD->getAttrs().isUnavailable(VD->getASTContext())`.

**Review by DougGregor — CHANGES_REQUESTED** [review]
This looks fantastic, thank you! Just a few minor concerns, then I'd like to get it tested and merged.

As for the GLKit overlay, I am absolutely fine with making the changes in the implementation of the overlay when we're getting the same API out of it. The overlay here is working around Clang importer limitations; we can fix the overlay when we remove the limitations.

It is possible that there are other sources like this overlay that will break with this change. Personally, I'd like to see if that happens in the wild before we go and add a Swift 4 version check + associated trickery here.

File: lib/ClangImporter/ImportDecl.cpp (hunk 2 above)
Comment (Fruneau) [inline lib/ClangImporter/ImportDecl.cpp]: This is not strictly equivalent since using `isUnavailable()` will cause the fields to be hidden for any unavailability reason (not just unconditional unavailability).

Comment (DougGregor) [inline lib/ClangImporter/ImportDecl.cpp]: Hmm... Can you at least pull this out into a separate static function, then? It's odd to have the loop inlined here.

Comment (Fruneau) [inline lib/ClangImporter/ImportDecl.cpp]: I actually repushed with `isUnavailable()` since after a few manual tests it does not seem to affect error reporting (I was worried that the error message for accessing an unimported field would be different from the one we get for an unavailable field, but it does not seem to be the case).

**Comment by jrose-apple** [comment]
@swift-ci Please smoke test

File: stdlib/public/SDK/GLKit/GLKMath.swift.gyb [hunk 3]
```diff
@@ -58,69 +48,15 @@ def defineSubscript(Type, limit):
 % for size in [2, 3, 4]:
 
 extension GLKMatrix${size} {
-  public typealias _Tuple = (${ ', '.join(['Float'] * (size * size)) })
```
Comment (slavapestov) [inline stdlib/public/SDK/GLKit/GLKMath.swift.gyb]: Really great to see this gunk go away.

**Comment by jrose-apple** [comment]
Just waiting to see if @DougGregor has any more feedback.

File: lib/ClangImporter/ImportDecl.cpp (hunk 2 above)
Comment (DougGregor) [inline lib/ClangImporter/ImportDecl.cpp]: Okay, thanks!

**Review by DougGregor — APPROVED** [review]

**Comment by DougGregor** [comment]
Nope, I'm happy with it now. Thanks!

**Comment by slavapestov** [comment]
@Fruneau Do you mind creating a new PR to add an entry to CHANGLEOG.md as well? We have several new ClangImporter features that might affect users so I'm following up with PR authors about documenting them.
