### PR TITLE
test: check static linking of FoundationNetworking

### PR DESCRIPTION
**Pull request by MaxDesiatov**
This trivial file when built with `-static-stdlib` is supposed to be statically linked with `FoundationNetworking`, but crashes on Ubuntu (and potentially all Linux distributions) with this error:

```
Foundation/NSSwiftRuntime.swift:409: Fatal error: You must link or load module FoundationNetworking to load non-file: URL content using String(contentsOf:…), Data(contentsOf:…), etc.
Trace/breakpoint trap
```

This was fixed in https://github.com/apple/swift-corelibs-foundation/pull/3135 for Swift 5.5, but regressed in Swift 5.6 and Swift 5.7. Having this test should help us prevent subsequent regressions.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test

**Comment by MaxDesiatov** [comment]
Closing this, as it's not a regression. 

This code having no references to `FoundationNetworking` causes a crash:

```swift
import Foundation

let str = try String(data: Data(contentsOf: URL(string: "https://httpbin.org/get")!), encoding: .utf8)
print(str)
```

`Data(contentsOf:)` weakly (indirectly) links `FoundationNetworking`, which leads to the linker stripping that as seemingly unused.

This snippet works perfectly fine when compiled with `swiftc -static-stdlib`:

```swift
import Foundation
import FoundationNetworking

_ = URLSession.shared

let str = try String(data: Data(contentsOf: URL(string: "https://httpbin.org/get")!), encoding: .utf8)
print(str)
```

Having a direct reference to symbols in FoundationNetworking (such as `URLSession`) is the recommended workaround as of Swift 5.7 and 5.6, and is likely to work in Swift 5.5 as well.

We're investigating if other solutions can be implemented in a future version of Swift.
